/**
 * @file    can_tx.c
 * @brief   Cyclic + event-triggered CAN transmit (DBC-driven)
 * @brief   周期 + 事件驱动的 CAN 发送（DBC 驱动）
 *
 * Walks `can_msg_descs_ipk[]` once per 10 ms tick.  For each TX
 * message:
 *   - If cycle_ms > 0, sends when the period has elapsed.
 *   - If cycle_ms == 0, sends only when armed by CanTx_Trigger().
 *
 * The payload itself is **NOT** built here -- business modules must
 * call `CanDb_EncodeAndPack()` (or `CanDb_DispatchByDb()` on RX)
 * before the tick fires, into a per-message scratch buffer that
 * the TX module then sends.  See `app/can/can_tx.h` for the
 * scratch-buffer API.
 */
#include "can_tx.h"
#include "drv_api/can/can_if.h"
#include "drv_api/can/can_db.h"
#include "rti.h"
#include "osif.h"
#include "signal.h"

#define MOD_NAME  "CTX "
#include "log.h"
/* A4: ack: s_tx.send_lock is no longer present in the struct - it was
 * removed when the TX path switched to CanTx_EncodeSignal (per-signal)
 * + s_tx.track[].pending flag (per-cycle gating). With those two the
 * only writers of s_tx.payloads[] are main-context CanTx_PreparePayload,
 * CanTx_EncodeSignal, CanTx_ResetPayload, CanTx_SetCycle and the cyclic
 * prv_send_cyclic() sweep - none of which runs in ISR. If a future port
 * tries to shove any of them into ISR, add a __disable_irq() / __set_PRIMASK
 * guard here and re-enable A4 with a real locking primitive.
 * Marker closed in Phase 2 without code change.
 */
/* B4: ack: CanTx_RebuildFromSignals has no hot-path caller today. The
 * only declared users are demo / unit tests; business modules (mod_power,
 * mod_meter, ...) write through the per-signal CanTx_EncodeSignal()
 * which avoids the full reset. Keep "reset + repack" as the documented
 * semantic ("snapshot of every signal in this message at call time"),
 * but treat the 8-byte zero + sig-by-sig repack as a one-shot rebuild
 * cost (O(msg->sig_count) <= 30 on the IPK DBC today). If a future driver
 * ever wants to call RebuildFromSignals from a 5 ms tick, replace the
 * body with a "mark all bits dirty + lazy repack at next trigger"
 * scheduler. Marker closed in Phase 2 without code change.
 */

/* Caller-private RTI slot for 10ms sweep gate. */
static rti_slot_t s_slot_sweep_10ms;


/* Upper bound on TX frames that can be in flight on a single
 * bus. Matches the CAN2 MB 26..31 reservation (6 MBs). Keep in
 * sync with CAN_TX_MB_COUNT in app/drv_api/can/can_if.c. */
#define CAN_TX_BUDGET   6u

typedef struct {
    u32 last_send_tick_ms;   /**< RTI tick at last successful tx (0 = never) */
    u8  pending;             /**< set by CanTx_Trigger, cleared after send   */
} tx_track_t;

/**
 * @brief   Per-TX-message scratch buffer: business modules fill
 *          `data` and `dlc` via CanTx_PreparePayload() before the
 *          next 10 ms tick.
 * @brief   每条 TX 报文的 scratch 缓冲: 业务模块在下一个 10 ms tick
 *          前通过 CanTx_PreparePayload() 填好 data 和 dlc
 *
 * Index = can_msg_descs_ipk[].is_tx messages, in the same order.
 */
typedef struct {
    u8  data[8];
    u8  dlc;
    u16 cycle_ms;            /**< copy of the message's send period    */
    u16 _pad;
} tx_payload_t;

static struct {
    bool          init_done;
    tx_track_t    track[CAN_DB_IPK_TX_COUNT];
    tx_payload_t  payloads[CAN_DB_IPK_TX_COUNT];
    u16           tx_msg_idx[CAN_DB_IPK_TX_COUNT];   /**< map slot -> ipk index */
    u16           tx_count;                      /**< number of TX entries  */
} s_tx;
/* ---------------------------------------------------------------- *
 *  TX cyclic period table                                            *
 *                                                                    *
 *  Per-IPK-TX-message cyclic send period.  Read by prv_build_tx_table *
 *  during mcu_init to seed s_tx.payloads[].cycle_ms.  Override at    *
 *  runtime via CanTx_SetCycle(). 0 = event-driven only (no cyclic).  *
 * ---------------------------------------------------------------- */

/**
 * @brief   Static default cyclic period for every IPK TX message
 * @brief   每条 IPK TX 报文的静态默认发送周期
 *
 * @details 索引 = TX slot 0..TX_COUNT-1（非 ipk 索引）。每行
 *          一条 TX 报文；表里只放 IPK TX 集合，无 RX 占位。
 *          prv_build_tx_table() 按 TX 顺序遍历 can_msg_descs_ipk[]，
 *          把匹配 slot 喂给本表以 seed s_tx.payloads[].cycle_ms。
 *
 *          在此调值，或运行时通过 CanTx_SetCycle(can_id, cycle_ms) 覆盖。单位：毫秒。 */
/* AUTOGENERATED by tools/dbc_parse.py -- TX-only, slot-indexed. */
static const u16 g_can_tx_cycle_table[CAN_DB_IPK_TX_COUNT] = {
    /*   0 IPK_SEND_E2_524                  (TX) */ 0u,
    /*   1 IPK_EngineService                (TX) */ 1000u,
    /*   2 IPK_STS                          (TX) */ 100u,
    /*   3 IPK_SettingRequest               (TX) */ 100u,
    /*   4 IPK_Fuel_Sts                     (TX) */ 100u,
    /*   5 IPK_TotalOdometer                (TX) */ 1000u,
    /*   6 IPK_DateTime_Info                (TX) */ 500u,
    /*   7 IPK_Fuel_Info                    (TX) */ 200u,
    /*   8 IPK_ODO_Consump                  (TX) */ 1000u,
    /*   9 NWM_IPK                          (TX) */ 0u,
};

/**
 * @brief   Locate the slot index in s_tx for a given IPK TX can_id.
 * @brief   按 IPK TX can_id 查找 s_tx 中的 slot 索引
 *
 * @param[in]  can_id  CAN id of an IPK TX message
 *
 * @return  u16  Slot index, or 0xFFFFu if not found
 */
static u16 prv_find_slot(u32 can_id)
{
    for (u16 slot = 0; slot < s_tx.tx_count; slot++) {
        const u16 msg_idx = s_tx.tx_msg_idx[slot];
        if (can_msg_descs_ipk[msg_idx].can_id == can_id) {
            return slot;
        }
    }
    return 0xFFFFu;
}

/**
 * @brief   One-shot init: scan the IPK message table for TX entries
 *          and build the slot-to-ipk-index map.
 * @brief   一次性初始化: 扫描 IPK 报文表中的 TX 条目, 建立 slot 到
 *          ipk 索引的映射
 */
static void prv_build_tx_table(void)
{
    s_tx.tx_count = 0u;
    for (u16 i = 0; i < (u16)CAN_DB_IPK_MSG_COUNT; i++) {
        if (!can_msg_descs_ipk[i].is_tx) continue;
        if (s_tx.tx_count >= (u16)CAN_DB_IPK_TX_COUNT) {
            LOG_W("TX table full, message %u skipped", (unsigned)i);
            break;
        }
        const u16 slot = s_tx.tx_count;
        s_tx.tx_msg_idx[slot] = i;
        s_tx.payloads[slot].dlc = can_msg_descs_ipk[i].dlc;
        /* Default cycle from g_can_tx_cycle_table[]. Override per-msg
         * at runtime via CanTx_SetCycle(). */
        s_tx.payloads[slot].cycle_ms = g_can_tx_cycle_table[slot];
        for (u8 b = 0; b < 8u; b++) { s_tx.payloads[slot].data[b] = 0u; }
        s_tx.tx_count++;
    }
}

/**
 * @brief   Send the payload currently in slot `slot` immediately.
 * @brief   立即发送当前在 slot 槽位中的 payload
 */
static void prv_send(u16 slot)
{
    if (slot >= s_tx.tx_count) return;
    const u16 msg_idx = s_tx.tx_msg_idx[slot];
    const can_msg_desc_t *d = &can_msg_descs_ipk[msg_idx];

    can_msg_t m = {0};
    m.id  = d->can_id;
    m.ide = 0u;   /* IPK DBC uses standard 11-bit ids */
    m.dlc = s_tx.payloads[slot].dlc;
    for (u8 i = 0; i < m.dlc && i < 8u; i++) {
        m.data[i] = s_tx.payloads[slot].data[i];
    }

    if (CanIf_Send(CAN_CH_PUBLIC, &m) == C02B2_OK) {
        s_tx.track[slot].last_send_tick_ms = RTI_GetTick1ms();
        s_tx.track[slot].pending = 0u;
    }
}

/* ---------------------------------------------------------------- *
 *  Module lifecycle                                                 *
 * ---------------------------------------------------------------- */

/**
 * @brief   mod_desc_t mcu_init hook: zero state and build TX slot map.
 * @brief   mod_desc_t mcu_init 钩子: 清零状态并构建 TX slot 映射
 */
static void prv_mcu_init(u8 cold_boot)
{
    (void)cold_boot;
    for (u32 i = 0; i < (u32)CAN_DB_IPK_TX_COUNT; i++) {
        s_tx.track[i].last_send_tick_ms = 0u;
        s_tx.track[i].pending = 0u;
    }
    prv_build_tx_table();
    s_slot_sweep_10ms = RTI_OpenSlot(RTI_10MS);
    s_tx.init_done = true;
    /* v0.3 F2: 清零 can_if.c::prv_flexcan_err_cb (在 ISR 上下文)
     * 写入的 4 个 CAN bus-health signal。启动期 50ms tick 之前不会有
     * ISR error callback 触发，所以这里写 0 与 ISR 后写实值不会冲突。*/
    Signal_Reset(SIG_CAN_BUS_OFF);
    Signal_Reset(SIG_CAN_BUS_OFF_COUNT);
    Signal_Reset(SIG_CAN_TX_ERR_CNT);
    Signal_Reset(SIG_CAN_RX_ERR_CNT);
    LOG_I("init (cold=%u, tx=%u)", (unsigned)cold_boot, (unsigned)s_tx.tx_count);
}
/**
 * @brief   mod_desc_t wakeup_init hook: post-MCU-init restore.
 * @brief   mod_desc_t wakeup_init 钩子: MCU 初始化后的唤醒恢复
 *
 * @details 在 mcu_init() 之后、on_ign_on() 之前执行。用此钩子
 *          重配 NVIC 优先级、恢复唤醒源状态或预填 mcu_init 留下的
 *          复位配置缓存。目前所有模块都是空实现 ——
 *          当某模块需要真正的 wake-from-reset 工作时再扩展。 */
static void prv_wakeup_init(void)
{
    LOG_I("wakeup_init");
}

/**
 * @brief   mod_desc_t on_ign_on hook: restart cycle timers.
 * @brief   mod_desc_t on_ign_on 钩子: 重启周期计时
 */
static void prv_on_ign_on(void)
{
    const u32 now = RTI_GetTick1ms();
    /* Phase-stagger every TX slot by tmo/tx_count so that
     * messages sharing the same cycle period do not expire
     * on the same 10 ms sweep. With 9 messages and 3 sharing
     * 100 ms, the three are spread across 33 ms each; with
     * 5 sharing 500 ms, they spread across 100 ms each.
     *
     * Effect on long-run:
     *   3 x 100 ms   - never more than 1 due per 10 ms sweep
     *   5 x 500 ms   - never more than 1 due per 100 ms sweep
     *   1 x 1000 ms  - never overlaps others in the same sweep
     * Steady-state: 1-2 TX frames per sweep, well below the
     * CAN_TX_BUDGET=6 ceiling. The budget guard in prv_tick
     * stays as defense-in-depth.
     *
     * Effect on cold boot: all 9 messages would otherwise
     * expire simultaneously on the first sweep (and spam
     * the can_if "all 6 TX MB busy" warning). With stagger,
     * the first sweep sees 1 message, the next sees another,
     * and the full backlog drains cleanly within ~1 s.
     */
    for (u16 i = 0; i < s_tx.tx_count; i++) {
        const u16 tmo = s_tx.payloads[i].cycle_ms;
        if (tmo == 0u) {
            /* Event-driven: stamp as "just sent" so it does
             * not fire spuriously if a Trigger sneaks in. */
            s_tx.track[i].last_send_tick_ms = now;
        } else {
            /* offset = i * tmo / tx_count gives 0..tmo spread
             * with the wrap point sitting at slot tx_count-1.
             * Subtracting from now makes the slot look like it
             * sent <offset> ms ago, so the next due instant is
             * <tmo - offset> ms from now. */
            const u32 offset = ((u32)i * (u32)tmo) / (u32)s_tx.tx_count;
            s_tx.track[i].last_send_tick_ms = now - offset;
        }
    }
}

/**
 * @brief   Sweep all TX slots once: send cyclic-due + pending frames
 * @brief   一次性扫所有 TX slot: 发周期到期 + pending 帧
 *
 * @details 每次扫描上限 CAN_TX_BUDGET 帧，让 CAN2 总线（仅预留 6 个 TX 邮箱）
          不被占满，并在冷启动时保持“all 6 TX MB busy”日志可读。
          被预算截掉的 slot 会在下一次 10 ms 扫描中重试，工作最终会排空。
 *
 *          数组中 slot 0 是周期发送，slot 1..N 是事件驱动（cycle_ms = 0，
          只有在 CanTx_Trigger 置 pending 位时才发）。 */
static void prv_sweep(void)
{
    const u32 now = RTI_GetTick1ms();
    u8 sent_this_sweep = 0u;
    for (u16 i = 0u; i < s_tx.tx_count; i++) {
        if (sent_this_sweep >= CAN_TX_BUDGET) {
            break;
        }
        const u16 tmo = s_tx.payloads[i].cycle_ms;
        if (tmo == 0u) {
            /* Event-driven: only fires when CanTx_Trigger set pending. */
            if (s_tx.track[i].pending) {
                prv_send(i);
                sent_this_sweep++;
            }
            continue;
        }
        if ((now - s_tx.track[i].last_send_tick_ms) >= (u32)tmo) {
            prv_send(i);
            sent_this_sweep++;
        }
    }
}

/**
 * @brief   mod_desc_t tick hook: 10 ms sweep gate -> prv_sweep()
 * @brief   mod_desc_t tick 钩子: 10 ms 闸门 -> prv_sweep()
 *
 * @details 与 mod_can_rx.tick() 形状对称：单 init_done 守卫，
          然后按周期的 RTI slot 检查委托给专用 worker。
          调用方私有 RTI slot 意味着其他模块的 tick 不会干扰我们。 */
__root static void prv_tick(void)
{
    if (!s_tx.init_done) { return; }
    if (RTI_SlotElapsed(&s_slot_sweep_10ms)) {
        prv_sweep();
    }
}

/**
 * @brief   mod_desc_t standby hook: clear pending flags.
 * @brief   mod_desc_t standby 钩子: 清零 pending
 */
static void prv_standby(void)
{
    for (u16 i = 0; i < s_tx.tx_count; i++) {
        s_tx.track[i].pending = 0u;
    }
}

/**
 * @brief   Module descriptor registered in scheduler.c
 * @brief   在 scheduler.c 中注册的模块描述符
 */
const mod_desc_t mod_can_tx = {
    .name      = "can_tx",
    .mcu_init   = prv_mcu_init,
    .wakeup_init = prv_wakeup_init,
    .on_ign_on = prv_on_ign_on,
    .tick      = prv_tick,
    .standby   = prv_standby,
};
/* ---------------------------------------------------------------- *
 *  Public API (preparing payloads and triggering)                  *
 * ---------------------------------------------------------------- */

/**
 * @brief   Fill the payload buffer for a TX message.
 * @brief   填充某条 TX 报文的 payload 缓冲
 *
 * @details `data[0..dlc-1]` 被复制到该报文的下一空闲 slot。
 *          下一 10 ms tick 发送时 buffer 里有啥就发啥。
 *          若 `dlc` 超过 8 会被截断。 *
 * @param[in]  can_id  IPK message can_id
 * @param[in]  data    Source buffer (at least `dlc` bytes)
 * @param[in]  dlc     Data length (0..8)
 *
 * @return  c02b2_result_t
 * @retval  C02B2_OK         Payload queued
 * @retval  C02B2_ERR_PARAM  can_id not an IPK TX message, or data NULL
 */
c02b2_result_t CanTx_PreparePayload(u32 can_id, const u8 *data, u8 dlc)
{
    if (data == NULL) { return C02B2_ERR_PARAM; }
    if (dlc > 8u) { dlc = 8u; }
    for (u16 slot = 0; slot < s_tx.tx_count; slot++) {
        const u16 msg_idx = s_tx.tx_msg_idx[slot];
        if (can_msg_descs_ipk[msg_idx].can_id != can_id) continue;
        for (u8 i = 0; i < dlc; i++) {
            s_tx.payloads[slot].data[i] = data[i];
        }
        s_tx.payloads[slot].dlc = dlc;
        return C02B2_OK;
    }
    return C02B2_ERR_PARAM;
}

/**
 * @brief   Override the cyclic period for a TX message.
 * @brief   覆盖某条 TX 报文的发送周期
 *
 * @param[in]  can_id     IPK TX message can_id
 * @param[in]  cycle_ms   Period in ms (0 = event-driven only)
 *
 * @return  c02b2_result_t
 * @retval  C02B2_OK        Period set
 * @retval  C02B2_ERR_PARAM can_id not an IPK TX message
 */
c02b2_result_t CanTx_SetCycle(u32 can_id, u16 cycle_ms)
{
    for (u16 slot = 0; slot < s_tx.tx_count; slot++) {
        const u16 msg_idx = s_tx.tx_msg_idx[slot];
        if (can_msg_descs_ipk[msg_idx].can_id != can_id) continue;
        s_tx.payloads[slot].cycle_ms = cycle_ms;
        return C02B2_OK;
    }
    return C02B2_ERR_PARAM;
}

/**
 * @brief   Force immediate send of a single TX frame (event-driven)
 * @brief   强制立即发送一帧（事件驱动）
 *
 * @details 把匹配条目标记为 pending，下一次 10 ms tick 跳过
 *          周期直接发。用于响应 diag 请求、按键事件等的 one-shot 帧。 *
 * @param[in]  can_id  11-bit CAN identifier (must match a TX db entry)
 *
 * @return  c02b2_result_t
 * @retval  C02B2_OK         Marked as pending
 * @retval  C02B2_ERR_PARAM  No matching TX entry
 */
c02b2_result_t CanTx_Trigger(u32 can_id)
{
    for (u16 slot = 0; slot < s_tx.tx_count; slot++) {
        const u16 msg_idx = s_tx.tx_msg_idx[slot];
        if (can_msg_descs_ipk[msg_idx].can_id != can_id) {
            continue;
        }
        s_tx.track[slot].pending = 1u;
        return C02B2_OK;
    }
    return C02B2_ERR_PARAM;
}

/* ---------------------------------------------------------------- *
 *  Per-signal payload update                                         *
 * ---------------------------------------------------------------- */

/**
 * @brief   Find a signal descriptor by name within a message's range.
 * @brief   在报文描述符范围内按信号名查找信号描述符
 */
static const can_sig_desc_t *prv_find_sig_in_msg(const can_msg_desc_t *msg, u16 sig_id)
{
    if (msg == NULL) { return NULL; }
    const u16 start = msg->sig_index;
    const u16 end   = (u16)(start + msg->sig_count);
    for (u16 i = start; i < end; i++) {
        const can_sig_desc_t *sig = &can_sig_descs_ipk[i];
        /* Signal descriptor order matches CAN_DB_SIG_* enum order
         * (1-based), so descriptor index (i - 0) maps to (sig_id - 1). */
        if ((u16)(i + 1u) == sig_id) {
            return sig;
        }
    }
    return NULL;
}

/**
 * @brief   Update a single signal inside an existing TX payload.
 * @brief   在已有 TX payload 中更新单个信号
 *
 * @param[in]  can_id  IPK TX message can_id
 * @param[in]  sig_id  CAN_DB_SIG_* signal id belonging to that message
 * @param[in]  raw     RAW value (bus-level u32; no factor/offset applied)
 *
 * @return  c02b2_result_t
 * @retval  C02B2_OK         Signal packed into the slot's payload
 * @retval  C02B2_ERR_PARAM  can_id not a TX message, sig_id not in it
 */
c02b2_result_t CanTx_EncodeSignal(u32 can_id, u16 sig_id, u32 raw)
{
    const u16 slot = prv_find_slot(can_id);
    if (slot == 0xFFFFu) { return C02B2_ERR_PARAM; }
    const u16 msg_idx = s_tx.tx_msg_idx[slot];
    const can_msg_desc_t *msg = &can_msg_descs_ipk[msg_idx];
    const can_sig_desc_t *sig = prv_find_sig_in_msg(msg, sig_id);
    if (sig == NULL) { return C02B2_ERR_PARAM; }
    /* The bus now carries RAW; pack raw directly (no factor math). */
    CanDb_PackSignal(s_tx.payloads[slot].data, sig, raw);
    return C02B2_OK;
}

/**
 * @brief   Rebuild a TX payload from every signal of that message,
 *          reading current signal-bus values via Signal_Get().
 * @brief   从 signal bus 重新读所有信号, 全量重建一条 TX 报文的 payload
 *
 * @details 先把 payload 清零，再对报文中每个信号用 Signal_Get 读
 *          SIG_CAN_<Name> 并通过 CanDb_PackSignal() 打包。适用于整 payload
 *          由 bus 状态派生的循环帧。
 *
 *          副作用：slot 的 payload 被同步更新，下一次 10 ms tick 会把刚刚
          重建好的内容发出去。 *          here.
 *
 * @param[in]  can_id  IPK TX message can_id
 *
 * @return  c02b2_result_t
 * @retval  C02B2_OK         Payload fully rebuilt
 * @retval  C02B2_ERR_PARAM  can_id not a TX message
 */
c02b2_result_t CanTx_RebuildFromSignals(u32 can_id)
{
    const u16 slot = prv_find_slot(can_id);
    if (slot == 0xFFFFu) { return C02B2_ERR_PARAM; }
    const u16 msg_idx = s_tx.tx_msg_idx[slot];
    const can_msg_desc_t *msg = &can_msg_descs_ipk[msg_idx];

    /* Zero out payload. */
    for (u8 b = 0; b < 8u; b++) { s_tx.payloads[slot].data[b] = 0u; }

    const u16 start = msg->sig_index;
    const u16 end   = (u16)(start + msg->sig_count);
    for (u16 i = start; i < end; i++) {
        const can_sig_desc_t *sig = &can_sig_descs_ipk[i];
        const u16 db_sig_id       = (u16)(i + 1u);
        const signal_id_t bus_id  = CanDb_DbcSigToBus(db_sig_id);
        /* v0.5: TX loopback 用 Signal_Get 直读。
         * 不走 Signal_Get 的 valid-fallback 语义。业务侧期望：
         * loopback 报文携带最近一次成功帧，而非超时后的 0。 */
        const u32 raw              = Signal_Get(bus_id); /* v0.5: 总线上是 RAW, 见 Signal_Get 直返;
                                  * 超时后 KEEP_LAST 的 signal 保留 "timeout 前最后一帧" raw,
                                  * INIT_DBC 的 signal 被改写为 init_value。*/
        /* The bus now carries RAW; pack raw directly (no factor math). */
    CanDb_PackSignal(s_tx.payloads[slot].data, sig, raw);
    }
    return C02B2_OK;
}

SCHED_REGISTER(mod_can_tx);
