/**
 * @file    can_rx.c
 * @brief   CAN receive dispatcher + timeout monitor
 * @brief   CAN 接收分发 + 超时监控
 *
 * Drains the FLEXCAN RX ring at 5 ms ticks; for each popped frame
 * looks up the IPK message descriptor in `can_msg_descs_ipk[]` and
 * dispatches it via `CanDb_DispatchByDb`.  Unknown IDs are logged
 * at DEBUG (could be a future frame).
 *
 * A 50 ms timer walks the descriptor table to refresh
 * SIG_CAN_RX_TIMEOUT_MAP.
 */
#include "can_rx.h"
#include "drv_api/can/can_if.h"
#include "drv_api/can/can_db.h"
#include "rti.h"
#include "signal.h"

#define LOG_NAME  "CRX "
#include "log.h"

#define MAX_RX_TRACKED  64u   /**< bitmap width of SIG_CAN_RX_TIMEOUT_MAP */

typedef struct {
    u32 last_rx_tick_ms;  /**< RTI tick at last successful rx (0 = never) */
} rx_track_t;

static struct {
    bool       init_done;
    rx_track_t track[MAX_RX_TRACKED];
} s_rx;
/* ---------------------------------------------------------------- *
 *  RX timeout table                                                  *
 *                                                                    *
 *  Per-IPK-message receive timeout.  Read by prv_check_timeouts()   *
 *  every 50 ms; bit idx in SIG_CAN_RX_TIMEOUT_MAP is set when       *
 *  (now - last_rx_tick_ms[idx]) > timeout_ms[idx].                  *
 *                                                                    *
 *  0 = no monitoring.  Indices match can_msg_descs_ipk[]. The DBC   *
 *  itself has no notion of cycle/timeout so this hand-authored      *
 *  table is the source of truth.                                    *
 * ---------------------------------------------------------------- */

/**
 * @brief   Static default receive timeout for every IPK message
 * @brief   每条 IPK 报文的静态默认接收超时
 *
 * @details Index matches `can_msg_descs_ipk[]`. The CANalyzer /
 *          network analysis team fills this in once the bus trace
 *          is available; until then the table is permissive (0 =
 *          no monitoring) so the cluster boots clean.
 *
 *          Typical rule of thumb: cycle * 3, rounded up to the
 *          nearest 50 ms. Units: milliseconds.
 */
/* AUTOGENERATED by tools/dbc_parse.py - regenerated by hand from can_db_ipk_gen.c with timeout_ms = cycle * 3 (placeholder). */
static const u16 g_can_rx_timeout_table[CAN_DB_IPK_MSG_COUNT] = {
    /*   0 MMI_DateTime_Msg                 (RX) */ 0u,
    /*   1 MMI_GPS_Info5                    (RX) */ 0u,
    /*   2 MMI_Status_Info                  (RX) */ 0u,
    /*   3 MMI_Safety_Info                  (RX) */ 0u,
    /*   4 MMI_SOCSet                       (RX) */ 0u,
    /*   5 EMS_EngRelateTrqSts              (RX) */ 0u,
    /*   6 EMS_EngineRPM                    (RX) */ 0u,
    /*   7 EMS_EngineDriverInfo             (RX) */ 0u,
    /*   8 EMS_EnginePatsBatteryStat        (RX) */ 0u,
    /*   9 EMS_OBD_Info                     (RX) */ 0u,
    /*  10 EGSM_Status                      (RX) */ 0u,
    /*  11 OBC_Sts                          (RX) */ 0u,
    /*  12 OBC_Curr                         (RX) */ 0u,
    /*  13 OBC_Failmode                     (RX) */ 0u,
    /*  14 BMSH_sts                         (RX) */ 0u,
    /*  15 BMSH_Battery_chgstate            (RX) */ 0u,
    /*  16 BMSH_CellTempLimitValue          (RX) */ 0u,
    /*  17 VCU_Ctrl                         (RX) */ 0u,
    /*  18 VCU_InforCAN                     (RX) */ 0u,
    /*  19 VCU_DCDC_Ctrl                    (RX) */ 0u,
    /*  20 VCU_CSControl1                   (RX) */ 0u,
    /*  21 VCU_ModeControl                  (RX) */ 0u,
    /*  22 IPU_TrqSpd                       (RX) */ 0u,
    /*  23 IPU_Sts                          (RX) */ 0u,
    /*  24 AVAS_DisabledSts                 (RX) */ 0u,
    /*  25 ACU_ChimeTelltaleReq             (RX) */ 0u,
    /*  26 EPS_InformSts                    (RX) */ 0u,
    /*  27 ESC_Status                       (RX) */ 0u,
    /*  28 ESC_DriverRemind                 (RX) */ 0u,
    /*  29 ESC_Regen                        (RX) */ 0u,
    /*  30 RSRSR_InformStatus               (RX) */ 0u,
    /*  31 FCS_ALAD_Status                  (RX) */ 0u,
    /*  32 FCS_SLIF_IHBC_Status             (RX) */ 0u,
    /*  33 FCS_Road_Status                  (RX) */ 0u,
    /*  34 FCS_ELK_Status                   (RX) */ 0u,
    /*  35 FCS_AEB                          (RX) */ 0u,
    /*  36 FCS_Display                      (RX) */ 0u,
    /*  37 FCS_FrontObject                  (RX) */ 0u,
    /*  38 FCS_FrontSideObject              (RX) */ 0u,
    /*  39 AC_ReqSts                        (RX) */ 0u,
    /*  40 TPMS_TyreDataInfo                (RX) */ 0u,
    /*  41 TPMS_TempStatusInfo              (RX) */ 0u,
    /*  42 BCM_LightChimeReq                (RX) */ 0u,
    /*  43 BCM_LDoorWindowState             (RX) */ 0u,
    /*  44 BCM_RDoorWindowState             (RX) */ 0u,
    /*  45 BCM_StateUpdate                  (RX) */ 0u,
    /*  46 BCM_SunroofState                 (RX) */ 0u,
    /*  47 PEPS_KeyReminder                 (RX) */ 0u,
    /*  48 GW_PEPS_Information              (RX) */ 0u,
    /*  49 GW_BCM_Information               (RX) */ 0u,
    /*  50 VCU_DriverTqInfo                 (RX) */ 0u,
    /*  51 BMSH_General                     (RX) */ 0u,
    /*  52 BMSH_VoltCurr                    (RX) */ 0u,
    /*  53 BMSH_OBC_Control                 (RX) */ 0u,
    /*  54 BMSH_Info                        (RX) */ 0u,
    /*  55 EcmChas2Fr92                     (RX) */ 0u,
    /*  56 EcmChas2Fr93                     (RX) */ 0u,
    /*  57 EcmChas2Fr33                     (RX) */ 0u,
    /*  58 PCM_Temperature                  (RX) */ 0u,
    /*  59 PCM_Warning                      (RX) */ 0u,
    /*  60 PcmChas1Fr19                     (RX) */ 0u,
    /*  61 IPU_Temperature                  (RX) */ 0u,
    /*  62 IPU_Warning                      (RX) */ 0u,
    /*  63 TRM_StatusInfo                   (RX) */ 0u,
    /*  64 IPK_EngineService                (TX) */ 0u,  /* TX row, not monitored */
    /*  65 IPK_STS                          (TX) */ 0u,  /* TX row, not monitored */
    /*  66 IPK_SettingRequest               (TX) */ 0u,  /* TX row, not monitored */
    /*  67 IPK_Fuel_Sts                     (TX) */ 0u,  /* TX row, not monitored */
    /*  68 IPK_TotalOdometer                (TX) */ 0u,  /* TX row, not monitored */
    /*  69 IPK_DateTime_Info                (TX) */ 0u,  /* TX row, not monitored */
    /*  70 IPK_Fuel_Info                    (TX) */ 0u,  /* TX row, not monitored */
    /*  71 IPK_ODO_Consump                  (TX) */ 0u,  /* TX row, not monitored */
    /*  72 NWM_IPK                          (TX) */ 0u,  /* TX row, not monitored */
};

/* ---------------------------------------------------------------- *
 *  Lookup helpers (DBC-driven)                                      *
 * ---------------------------------------------------------------- */

/**
 * @brief   Find the index of an IPK message in the descriptor table.
 * @brief   在 IPK 报文描述符表中查找索引
 *
 * @details Linear search; the IPK test batch has < 32 entries.
 *          Returns 0xFFFFu when not found.
 *
 * @param[in]  can_id  11-bit standard CAN identifier
 *
 * @return  u16  Index into can_msg_descs_ipk[], or 0xFFFFu
 */
static u16 prv_find_ipk_index(u32 can_id)
{
    for (u16 i = 0; i < (u16)CAN_DB_IPK_MSG_COUNT; i++) {
        if (can_msg_descs_ipk[i].can_id == can_id) {
            return i;
        }
    }
    return 0xFFFFu;
}

/**
 * @brief   Look up the timeout configured for a given message.
 * @brief   查找某条报文配置的超时值
 *
 * @details Reads a per-message timeout from a small static table.
 *          The DBC has no notion of cycle/timeout so we keep a
 *          hand-authored parallel table (see prv_timeout_table[]).
 *
 * @param[in]  idx  Index into can_msg_descs_ipk[]
 *
 * @return  u16  Timeout in milliseconds (0 = do not monitor)
 */
static u16 prv_timeout_for(u16 idx)
{
    if (idx >= (u16)CAN_DB_IPK_MSG_COUNT) {
        return 0u;
    }
    /* Look up the per-message timeout from g_can_rx_timeout_table[].
     * The DBC has no notion of cycle/timeout so this hand-authored
     * parallel table is the source of truth.  Index matches
     * can_msg_descs_ipk[]. 0 = do not monitor. */
    return g_can_rx_timeout_table[idx];
}

/* ---------------------------------------------------------------- *
 *  Module lifecycle                                                 *
 * ---------------------------------------------------------------- */

/**
 * @brief   mod_desc_t mcu_init hook: zero the timeout table.
 * @brief   mod_desc_t mcu_init 钩子: 清零超时表
 *
 * @param[in]  cold_boot  1 = cold boot, 0 = warm boot
 */
static void prv_mcu_init(u8 cold_boot)
{
    (void)cold_boot;
    for (u32 i = 0; i < MAX_RX_TRACKED; i++) {
        s_rx.track[i].last_rx_tick_ms = 0u;
    }
    s_rx.init_done = true;
    LOG_I("init (cold=%u, registered_rx=%u)", (unsigned)cold_boot, (unsigned)CAN_DB_IPK_RX_COUNT);
}
/**
 * @brief   mod_desc_t wakeup_init hook: post-MCU-init restore.
 * @brief   mod_desc_t wakeup_init 钩子: MCU 初始化后的唤醒恢复
 *
 * @details Runs after mcu_init() and before on_ign_on(). Use this
 *          hook to re-arm NVIC priorities, restore wake-source
 *          state, or prime caches that mcu_init left in a known
 *          reset configuration. Currently a stub for all modules
 *          - extend when a module needs real wake-from-reset work.
 */
static void prv_wakeup_init(void)
{
    LOG_I("wakeup_init");
}

/**
 * @brief   mod_desc_t on_ign_on hook: clear all timeout flags.
 * @brief   mod_desc_t on_ign_on 钩子: 清零所有超时标志
 */
static void prv_on_ign_on(void)
{
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_LO, 0); Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_HI, 0);
}
/**
 * @brief   Drain pending frames from the RX ring and dispatch via
 *          the IPK descriptor table.
 * @brief   排空接收环中的待处理帧, 并通过 IPK 描述符表分发
 *
 * @details For each popped frame:
 *          1. Look up the IPK descriptor by can_id.
 *          2. If found, hand the descriptor + payload to
 *             `CanDb_DispatchByDb` which decodes every signal.
 *          3. Stamp `last_rx_tick_ms` so the timeout monitor sees
 *             the entry as fresh.
 *          Frames whose id is not in the IPK table are logged at
 *          DEBUG (could be a future frame or vendor-specific msg).
 */
static void prv_drain(void)
{
    can_msg_t m;
    u32 drained = 0;
    while (CanIf_PopRx(&m)) {
        drained++;
        const u16 idx = prv_find_ipk_index(m.id);
        if (idx != 0xFFFFu) {
            /* Known frame: hand off to the DBC dispatcher. */
            CanDb_DispatchByDb(&can_msg_descs_ipk[idx], m.data);
            if (idx < MAX_RX_TRACKED) {
                s_rx.track[idx].last_rx_tick_ms = RTI_GetTick1ms();
            }
        } else {
            /* Unknown id -- not necessarily an error. */
            LOG_D("rx id=0x%X (no DBC entry)", (unsigned)m.id);
        }
    }
    if (drained > 0u) {
        LOG_D("drained %u frame(s), pending=%u", (unsigned)drained, (unsigned)CanIf_RxPending());
    }
}

/**
 * @brief   Walk the IPK descriptor table and update
 *          SIG_CAN_RX_TIMEOUT_MAP_LO / SIG_CAN_RX_TIMEOUT_MAP_HI.
 * @brief   遍历 IPK 描述符表, 更新 SIG_CAN_RX_TIMEOUT_MAP_LO/HI
 *
 * @details For every RX descriptor with a configured timeout, set
 *          bit `idx` in either LO (idx 0..31) or HI (idx 32..63) if
 *          (now - last_rx_tick_ms[idx]) > timeout_ms.  TX rows
 *          (g_can_rx_timeout_table[i] == 0) are skipped.  Indices
 *          >= MAX_RX_TRACKED (64) are silently skipped.
 */
static void prv_check_timeouts(void)
{
    const u32 now = RTI_GetTick1ms();
    u32 map_lo = 0u;
    u32 map_hi = 0u;
    for (u16 i = 0; i < (u16)CAN_DB_IPK_MSG_COUNT; i++) {
        const u16 tmo = prv_timeout_for(i);
        if (tmo == 0u) continue;
        if (i >= MAX_RX_TRACKED) break;
        const u32 last = s_rx.track[i].last_rx_tick_ms;
        if ((now - last) <= (u32)tmo) continue;
        if (i < 32u) {
            map_lo |= (1u << i);
        } else {
            map_hi |= (1u << (i - 32u));
        }
    }
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_LO, (int32_t)map_lo);
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_HI, (int32_t)map_hi);
}

/**
 * @brief   mod_desc_t tick hook: drain @ 5 ms, timeouts @ 50 ms.
 * @brief   mod_desc_t tick 钩子: 5 ms 排空接收环, 50 ms 检查超时
 */
static void prv_tick(void)
{
    if (!s_rx.init_done) { return; }
    if (RTI_IsElapsed(RTI_5MS))  { prv_drain(); }
    if (RTI_IsElapsed(RTI_50MS)) { prv_check_timeouts(); }
}

/**
 * @brief   mod_desc_t standby hook: clear all timeout flags.
 * @brief   mod_desc_t standby 钩子: 清零所有超时标志
 */
static void prv_standby(void)
{
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_LO, 0); Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_HI, 0);
}

/**
 * @brief   Module descriptor registered in scheduler.c
 * @brief   在 scheduler.c 中注册的模块描述符
 */
const mod_desc_t mod_can_rx = {
    .name      = "can_rx",
    .mcu_init   = prv_mcu_init,
    .wakeup_init = prv_wakeup_init,
    .on_ign_on = prv_on_ign_on,
    .tick      = prv_tick,
    .standby   = prv_standby,
};