/**
 * @file    can_rx.c
 * @brief   CAN receive dispatcher + timeout monitor
 * @brief   CAN 接收分发 + 超时监控
 *
 * Drains the FLEXCAN RX ring at 5 ms ticks; for each popped frame
 * looks up the IPK message descriptor in `can_msg_descs_ipk[]` and
 * dispatches it via `CanDb_DispatchByDb`.  Unknown IDs are logged
 * at DEBUG (could be a future frame).
 *
 * Timeout monitor (50 ms tick) walks the 96-entry
 * `s_bit_to_can_id[]` lookup table (Sentinel strategy) and updates
 * SIG_CAN_RX_TIMEOUT_MAP_{LO,HI,HI2}.  bit-N is per-CAN-ID so DBC
 * message reordering does not shift the bit numbering.
 */
#include "can_rx.h"
#include "drv_api/can/can_if.h"
#include "drv_api/can/can_db.h"
#include "rti.h"
#include "signal.h"

#define LOG_NAME  "CRX "
#include "log.h"

/* Caller-private RTI slots (replaces shared RTI_IsElapsed via RTI slot API). */
static rti_slot_t s_slot_5ms;
static rti_slot_t s_slot_50ms;

#define MAX_RX_TRACKED  96u   /**< bitmap width of SIG_CAN_RX_TIMEOUT_MAP (LO+HI+HI2 = 3 slots x 32 bit) */

/* Small LRU of unknown CAN ids already announced via LOG_I. We
 * want a noisy bus (0x371 test id, vendor-specific frames) to
 * surface once per id, not every 5 ms. 8 slots covers the usual
 * test-bench traffic; older entries get evicted FIFO. */
#define MAX_RX_UNKNOWN_LOG  8u

typedef struct {
    u32 last_rx_tick_ms;  /**< RTI tick at last successful rx (0 = never) */
} rx_track_t;

/** Per-IPK-message raw frame cache.
 *  Indexed by can_msg_descs_ipk[] (NOT by can_id directly, because two
 *  messages cannot share an id but the table is the SoT for "which ids
 *  do we know about").  `valid` flips to 1 the first time a frame arrives
 *  for that index; the cached bytes are then refreshed on every match.
 */
typedef struct {
    bool valid;
    can_msg_t frame;
    u32  rx_tick_ms;
} rx_raw_cache_t;

static struct {
    bool       init_done;
    rx_track_t track[MAX_RX_TRACKED];
    rx_raw_cache_t raw[CAN_DB_IPK_MSG_COUNT];  /**< most-recent raw frame */
    u32        seen_unknown_ids[MAX_RX_UNKNOWN_LOG];  /**< FIFO of announced unknown ids */
    u8         seen_unknown_count;                    /**< 0..MAX_RX_UNKNOWN_LOG */
    u8         seen_unknown_next;                     /**< next FIFO write index */
} s_rx;
/* ---------------------------------------------------------------- *
 *  RX timeout table                                                  *
 *                                                                    *
 *  Per-IPK-message receive timeout.  Read by prv_check_timeouts()   *
 *  every 50 ms; bit idx in SIG_CAN_RX_TIMEOUT_MAP is set when       *
 *  (now - last_rx_tick_ms[idx]) > timeout_ms[idx].                  *
 *                                                                    *
 *  0 = no monitoring.  Indices match can_msg_descs_ipk[]. The DBC   *
 *  itself has no notion of cycle/timeout so this hand-authored      *
 *  table is the source of truth.                                    *
 * ---------------------------------------------------------------- */

/**
 * @brief   Static default receive timeout for every IPK message
 * @brief   每条 IPK 报文的静态默认接收超时
 *
 * @details Index matches `can_msg_descs_ipk[]`. The CANalyzer /
 *          network analysis team fills this in once the bus trace
 *          is available; until then the table is permissive (0 =
 *          no monitoring) so the cluster boots clean.
 *
 *          Typical rule of thumb: cycle * 3, rounded up to the
 *          nearest 50 ms. Units: milliseconds.
 */
/* AUTOGENERATED by tools/dbc_parse.py - regenerated by hand from can_db_ipk_gen.c with timeout_ms = cycle * 3 (placeholder). */
static const u16 g_can_rx_timeout_table[CAN_DB_IPK_MSG_COUNT] = {
    /*   0 MMI_DateTime_Msg                 (RX) */ 1500u,  /* cycle * 3, round 50 ms */
    /*   1 MMI_GPS_Info5                    (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*   2 MMI_Status_Info                  (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*   3 MMI_Safety_Info                  (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*   4 MMI_SOCSet                       (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*   5 EMS_EngRelateTrqSts              (RX) */ 300u,  /* cycle * 3, round 50 ms */
    /*   6 EMS_EngineRPM                    (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*   7 EMS_EngineDriverInfo             (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*   8 EMS_EnginePatsBatteryStat        (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*   9 EMS_OBD_Info                     (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  10 EGSM_Status                      (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  11 OBC_Sts                          (RX) */ 300u,  /* cycle * 3, round 50 ms */
    /*  12 OBC_Curr                         (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  13 OBC_Failmode                     (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  14 BMSH_sts                         (RX) */ 300u,  /* cycle * 3, round 50 ms */
    /*  15 BMSH_Battery_chgstate            (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  16 BMSH_CellTempLimitValue          (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  17 VCU_Ctrl                         (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  18 VCU_InforCAN                     (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  19 VCU_DCDC_Ctrl                    (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  20 VCU_CSControl1                   (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  21 VCU_ModeControl                  (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  22 IPU_TrqSpd                       (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  23 IPU_Sts                          (RX) */ 300u,  /* cycle * 3, round 50 ms */
    /*  24 AVAS_DisabledSts                 (RX) */ 300u,  /* cycle * 3, round 50 ms */
    /*  25 ACU_ChimeTelltaleReq             (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  26 EPS_InformSts                    (RX) */ 300u,  /* cycle * 3, round 50 ms */
    /*  27 ESC_Status                       (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  28 ESC_DriverRemind                 (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  29 ESC_Regen                        (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  30 RSRSR_InformStatus               (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  31 FCS_ALAD_Status                  (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  32 FCS_SLIF_IHBC_Status             (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  33 FCS_Road_Status                  (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  34 FCS_ELK_Status                   (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  35 FCS_AEB                          (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  36 FCS_Display                      (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  37 FCS_FrontObject                  (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  38 FCS_FrontSideObject              (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  39 AC_ReqSts                        (RX) */ 300u,  /* cycle * 3, round 50 ms */
    /*  40 TPMS_TyreDataInfo                (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  41 TPMS_TempStatusInfo              (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  42 BCM_LightChimeReq                (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  43 BCM_LDoorWindowState             (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  44 BCM_RDoorWindowState             (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  45 BCM_StateUpdate                  (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  46 BCM_SunroofState                 (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  47 PEPS_KeyReminder                 (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  48 GW_PEPS_Information              (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  49 GW_BCM_Information               (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  50 VCU_DriverTqInfo                 (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  51 BMSH_General                     (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  52 BMSH_VoltCurr                    (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  53 BMSH_OBC_Control                 (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  54 BMSH_Info                        (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  55 EcmChas2Fr92                     (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  56 EcmChas2Fr93                     (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  57 EcmChas2Fr33                     (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  58 PCM_Temperature                  (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  59 PCM_Warning                      (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  60 PcmChas1Fr19                     (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  61 IPU_Temperature                  (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  62 IPU_Warning                      (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  63 TRM_StatusInfo                   (RX) */ 3000u,  /* cycle * 3, round 50 ms */
    /*  64 IPK_EngineService                (TX) */ 0u,  /* TX row, not monitored */
    /*  65 IPK_STS                          (TX) */ 0u,  /* TX row, not monitored */
    /*  66 IPK_SettingRequest               (TX) */ 0u,  /* TX row, not monitored */
    /*  67 IPK_Fuel_Sts                     (TX) */ 0u,  /* TX row, not monitored */
    /*  68 IPK_TotalOdometer                (TX) */ 0u,  /* TX row, not monitored */
    /*  69 IPK_DateTime_Info                (TX) */ 0u,  /* TX row, not monitored */
    /*  70 IPK_Fuel_Info                    (TX) */ 0u,  /* TX row, not monitored */
    /*  71 IPK_ODO_Consump                  (TX) */ 0u,  /* TX row, not monitored */
    /*  72 NWM_IPK                          (TX) */ 0u,  /* TX row, not monitored */
};

/* ---------------------------------------------------------------- *
 *  Lookup helpers (DBC-driven)                                      *
 * ---------------------------------------------------------------- */

/**
 * @brief   Find the index of an IPK message in the descriptor table.
 * @brief   在 IPK 报文描述符表中查找索引
 *
 * @details Linear search; the IPK test batch has < 32 entries.
 *          Returns 0xFFFFu when not found.
 *
 * @param[in]  can_id  11-bit standard CAN identifier
 *
 * @return  u16  Index into can_msg_descs_ipk[], or 0xFFFFu
 */
static u16 prv_find_ipk_index(u32 can_id)
{
    for (u16 i = 0; i < (u16)CAN_DB_IPK_MSG_COUNT; i++) {
        if (can_msg_descs_ipk[i].can_id == can_id) {
            return i;
        }
    }
    return 0xFFFFu;
}

/**
 * @brief   Look up the bit-N for a given CAN ID via the Sentinel table.
 * @brief   在 Sentinel 表中查找某 CAN ID 对应的 bit-N
 *
 * @details Linear search over s_bit_to_can_id[].  Returns 0xFFu when
 *          the CAN ID is not assigned a bit (deleted-DBC sentinel,
 *          reserved pool, or unknown ID).  O(96) worst case which
 *          is fine for a 50 ms tick on Cortex-M0+.
 *
 * @param[in]  can_id  11-bit standard CAN identifier
 *
 * @return  u8  bit index (0..95) or 0xFFu if not mapped
 */
static u8 prv_bit_for_can_id(u32 can_id)
{
    for (u8 b = 0u; b < (u8)CAN_BITMAP_MAX; b++) {
        if (s_bit_to_can_id[b] == can_id) {
            return b;
        }
    }
    return 0xFFu;
}

/**
 * @brief   Read the per-bit timeout (ms) from the existing per-idx table.
 * @brief   从既有的 per-idx 超时表中读取对应 bit 的超时值
 *
 * @details Translates bit-N back to the descriptor index so the
 *          hand-authored (or DBC-regenerated) g_can_rx_timeout_table
 *          can be re-used as-is.  TX rows return 0 (not monitored).
 *
 * @param[in]  bit  bit index 0..95
 *
 * @return  u16  Timeout in milliseconds (0 = do not monitor)
 */
static u16 prv_timeout_for_bit(u8 bit)
{
    if (bit >= (u8)CAN_BITMAP_MAX) {
        return 0u;
    }
    const u32 can_id = s_bit_to_can_id[bit];
    if (can_id == sentinel_unused) {
        return 0u;
    }
    const u16 idx = prv_find_ipk_index(can_id);
    if (idx == 0xFFFFu) {
        return 0u;
    }
    return g_can_rx_timeout_table[idx];
}

/* ---------------------------------------------------------------- *
 *  Module lifecycle                                                 *
 * ---------------------------------------------------------------- */

/**
 * @brief   mod_desc_t mcu_init hook: zero the timeout table.
 * @brief   mod_desc_t mcu_init 钩子: 清零超时表
 *
 * @param[in]  cold_boot  1 = cold boot, 0 = warm boot
 */
static void prv_mcu_init(u8 cold_boot)
{
    (void)cold_boot;
    for (u32 i = 0; i < MAX_RX_TRACKED; i++) {
        s_rx.track[i].last_rx_tick_ms = 0u;
    }
    s_slot_5ms  = RTI_OpenSlot(RTI_5MS);
    s_slot_50ms = RTI_OpenSlot(RTI_50MS);
    s_rx.init_done = true;
    s_rx.seen_unknown_count = 0u;
    s_rx.seen_unknown_next  = 0u;
    LOG_I("init (cold=%u, registered_rx=%u)", (unsigned)cold_boot, (unsigned)CAN_DB_IPK_RX_COUNT);
}
/**
 * @brief   mod_desc_t wakeup_init hook: post-MCU-init restore.
 * @brief   mod_desc_t wakeup_init 钩子: MCU 初始化后的唤醒恢复
 *
 * @details Runs after mcu_init() and before on_ign_on(). Use this
 *          hook to re-arm NVIC priorities, restore wake-source
 *          state, or prime caches that mcu_init left in a known
 *          reset configuration. Currently a stub for all modules
 *          - extend when a module needs real wake-from-reset work.
 */
static void prv_wakeup_init(void)
{
    LOG_I("wakeup_init");
}

/**
 * @brief   mod_desc_t on_ign_on hook: clear all timeout flags.
 * @brief   mod_desc_t on_ign_on 钩子: 清零所有超时标志
 */
static void prv_on_ign_on(void)
{
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_LO,  0);
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_HI,  0);
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_HI2, 0);
}
/**
 * @brief   Drain pending frames from the RX ring and dispatch via
 *          the IPK descriptor table.
 * @brief   排空接收环中的待处理帧, 并通过 IPK 描述符表分发
 *
 * @details For each popped frame:
 *          1. Look up the IPK descriptor by can_id.
 *          2. If found, hand the descriptor + payload to
 *             `CanDb_DispatchByDb` which decodes every signal.
 *          3. Stamp `last_rx_tick_ms` so the timeout monitor sees
 *             the entry as fresh.
 *          Frames whose id is not in the IPK table are logged at
 *          DEBUG (could be a future frame or vendor-specific msg).
 */
static void prv_drain(void)
{
    can_msg_t m;
    u32 drained = 0;
    while (CanIf_PopRx(&m)) {
        drained++;
        const u16 idx = prv_find_ipk_index(m.id);
        if (idx != 0xFFFFu) {
            /* Cache the raw frame so diag / demo modules can read
             * the full 8-byte payload without re-decoding every signal.
             * Cache index matches can_msg_descs_ipk[] order; the array
             * is sized to CAN_DB_IPK_MSG_COUNT so any idx is in range. */
            s_rx.raw[idx].frame     = m;
            s_rx.raw[idx].rx_tick_ms = RTI_GetTick1ms();
            s_rx.raw[idx].valid      = true;
            /* Known frame: hand off to the DBC dispatcher. */
            CanDb_DispatchByDb(&can_msg_descs_ipk[idx], m.data);
            /* Stamp the per-bit-N last-rx tick (Sentinel: bit-N is
             * stable across DBC reorders; the table is the SoT). */
            const u8 bit = prv_bit_for_can_id(m.id);
            if (bit < (u8)CAN_BITMAP_MAX) {
                s_rx.track[bit].last_rx_tick_ms = RTI_GetTick1ms();
            }
        } else {
            /* Unknown id: not necessarily an error (could be a
             * future-DBC frame or vendor-specific msg), but if we
             * have never announced it before we want to surface it
             * once at LOG_I so the operator can correlate with the
             * bus trace. Repeated unknown ids within the FIFO get
             * demoted to LOG_D to keep the log readable. */
            bool announced = false;
            for (u8 k = 0u; k < s_rx.seen_unknown_count; k++) {
                if (s_rx.seen_unknown_ids[k] == m.id) { announced = true; break; }
            }
            if (announced) {
                #if CAN_DEBUG_LOG
                LOG_D("rx id=0x%X (no DBC entry, already announced)", (unsigned)m.id);
                #endif
            } else {
                s_rx.seen_unknown_ids[s_rx.seen_unknown_next] = m.id;
                s_rx.seen_unknown_next = (u8)((s_rx.seen_unknown_next + 1u) % MAX_RX_UNKNOWN_LOG);
                if (s_rx.seen_unknown_count < MAX_RX_UNKNOWN_LOG) {
                    s_rx.seen_unknown_count++;
                }
                #if CAN_DEBUG_LOG
                LOG_I("rx id=0x%X (no DBC entry, first seen)", (unsigned)m.id);
                #endif
            }
        }
    }
    if (drained > 0u) {
        #if CAN_DEBUG_LOG
        LOG_D("drained %u frame(s), pending=%u", (unsigned)drained, (unsigned)CanIf_RxPending());
        #endif
    }
}

/**
 * @brief   Walk the IPK descriptor table and update the three
 *          bitmap slots of SIG_CAN_RX_TIMEOUT_MAP_{LO,HI,HI2}.
 * @brief   遍历 IPK 描述符表, 更新 SIG_CAN_RX_TIMEOUT_MAP_LO/HI/HI2
 *
 * @details For every RX descriptor with a configured timeout, set
 *          bit `idx` in LO/HI/HI2 if
 *          (now - last_rx_tick_ms[idx]) > timeout_ms[idx]:
 *            idx  0..31 -> MAP_LO  (bit (idx))
 *            idx 32..63 -> MAP_HI  (bit (idx - 32))
 *            idx 64..95 -> MAP_HI2 (bit (idx - 64))
 *          TX rows (g_can_rx_timeout_table[i] == 0) are skipped.
 *          Indices >= MAX_RX_TRACKED (96) are silently skipped.
 */
static void prv_check_timeouts(void)
{
    const u32 now = RTI_GetTick1ms();
    u32 map_lo  = 0u;
    u32 map_hi  = 0u;
    u32 map_hi2 = 0u;
    /* Walk the 96-bit Sentinel table.  sentinel_unused (DBC-deleted
     * or reserved-pool) bits are skipped by prv_timeout_for_bit()
     * returning 0, so they are permanently 0 in the bitmap. */
    for (u8 bit = 0u; bit < (u8)CAN_BITMAP_MAX; bit++) {
        const u16 tmo = prv_timeout_for_bit(bit);
        if (tmo == 0u) continue;
        const u32 last = s_rx.track[bit].last_rx_tick_ms;
        if ((now - last) <= (u32)tmo) continue;
        if (bit < 32u) {
            map_lo |= ((u32)1u << bit);
        } else if (bit < 64u) {
            map_hi |= ((u32)1u << (bit - 32u));
        } else {
            map_hi2 |= ((u32)1u << (bit - 64u));
        }
    }
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_LO,  map_lo);
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_HI,  map_hi);
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_HI2, map_hi2);
}

/**
 * @brief   mod_desc_t tick hook: drain @ 5 ms, timeouts @ 50 ms.
 * @brief   mod_desc_t tick 钩子: 5 ms 排空接收环, 50 ms 检查超时
 */
static void prv_tick(void)
{
    if (!s_rx.init_done) { return; }
    if (RTI_SlotElapsed(&s_slot_5ms))  { prv_drain(); }
    if (RTI_SlotElapsed(&s_slot_50ms)) { prv_check_timeouts(); }
}

/**
 * @brief   mod_desc_t standby hook: clear all timeout flags.
 * @brief   mod_desc_t standby 钩子: 清零所有超时标志
 */
static void prv_standby(void)
{
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_LO,  0);
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_HI,  0);
    (void)Signal_Set(SIG_CAN_RX_TIMEOUT_MAP_HI2, 0);
}

/* ---------------------------------------------------------------- *
 *  Public API: raw frame cache
 *
 *  Indexed lookup.  The cache is updated inside prv_drain(); the read
 *  API is safe to call from any tick (5 ms or slower) or from main().
 * ---------------------------------------------------------------- */
c02b2_result_t CanRx_GetLastRawFrame(u32 can_id, can_msg_t *out)
{
    if (out == NULL) {
        return C02B2_ERR_PARAM;
    }
    /* Linear scan of can_msg_descs_ipk[] is fine: 73 entries, called
     * from a 1 s demo tick -- no need for a hash. */
    for (u32 i = 0u; i < (u32)CAN_DB_IPK_MSG_COUNT; i++) {
        if (can_msg_descs_ipk[i].can_id != can_id) { continue; }
        if (can_msg_descs_ipk[i].is_tx != 0u) {
            /* TX entries have no RX cache; refuse. */
            return C02B2_ERR_PARAM;
        }
        if (!s_rx.raw[i].valid) {
            return C02B2_ERR_NOT_FOUND;
        }
        *out = s_rx.raw[i].frame;
        return C02B2_OK;
    }
    return C02B2_ERR_PARAM;   /* unknown can_id */
}

u32 CanRx_GetRawFrameCount(void)
{
    u32 n = 0u;
    for (u32 i = 0u; i < (u32)CAN_DB_IPK_MSG_COUNT; i++) {
        if (s_rx.raw[i].valid) { n++; }
    }
    return n;
}

/**
 * @brief   Module descriptor registered in scheduler.c
 * @brief   在 scheduler.c 中注册的模块描述符
 */
const mod_desc_t mod_can_rx = {
    .name      = "can_rx",
    .mcu_init   = prv_mcu_init,
    .wakeup_init = prv_wakeup_init,
    .on_ign_on = prv_on_ign_on,
    .tick      = prv_tick,
    .standby   = prv_standby,
};

SCHED_REGISTER(mod_can_rx);
