/* AUTOGENERATED by tools/dbc_parse.py -- do not edit by hand. */
#ifndef CAN_DB_IPK_GEN_H
#define CAN_DB_IPK_GEN_H

#include <stdint.h>
#include "can_db_codec.h"

/* Signal IDs -- order matches can_sig_descs_ipk[] */
typedef enum {
    CAN_DB_SIG_INVALID = 0, /* [  0] invalid sentinel */
    CAN_DB_SIG_IPK_RECV_E2_B7, /* [  1] */
    CAN_DB_SIG_IPK_RECV_E2_B6, /* [  2] */
    CAN_DB_SIG_IPK_RECV_E2_B5, /* [  3] */
    CAN_DB_SIG_IPK_RECV_E2_B4, /* [  4] */
    CAN_DB_SIG_IPK_RECV_E2_B3, /* [  5] */
    CAN_DB_SIG_IPK_RECV_E2_B2, /* [  6] */
    CAN_DB_SIG_IPK_RECV_E2_B1, /* [  7] */
    CAN_DB_SIG_IPK_RECV_E2_B0, /* [  8] */
    CAN_DB_SIG_MMI_Second, /* [  9] */
    CAN_DB_SIG_MMI_Minute, /* [ 10] */
    CAN_DB_SIG_MMI_Hour, /* [ 11] */
    CAN_DB_SIG_MMI_Day, /* [ 12] */
    CAN_DB_SIG_MMI_Month, /* [ 13] */
    CAN_DB_SIG_MMI_Year, /* [ 14] */
    CAN_DB_SIG_GPS_elevation_Info, /* [ 15] */
    CAN_DB_SIG_MMI_GPS_Info5_AliveCounter, /* [ 16] */
    CAN_DB_SIG_MMI_GPS_Info5_CheckSum, /* [ 17] */
    CAN_DB_SIG_MMI_RightSwStatus, /* [ 18] */
    CAN_DB_SIG_MMI_LeftSwStatus, /* [ 19] */
    CAN_DB_SIG_MMI_UpSwStatus, /* [ 20] */
    CAN_DB_SIG_MMI_DownSwStatus, /* [ 21] */
    CAN_DB_SIG_MMI_ConfirmSwStatus, /* [ 22] */
    CAN_DB_SIG_MMI_ReturnSwStatus, /* [ 23] */
    CAN_DB_SIG_MMI_WorkMode, /* [ 24] */
    CAN_DB_SIG_MMI_SkinMode, /* [ 25] */
    CAN_DB_SIG_MMI_HUDAciveRequest, /* [ 26] */
    CAN_DB_SIG_MMI_AVH_Request, /* [ 27] */
    CAN_DB_SIG_MMI_OdometerClearReq, /* [ 28] */
    CAN_DB_SIG_MMI_SkinModeCorrelativeSts, /* [ 29] */
    CAN_DB_SIG_MMI_SVA_AudibleWarningOption, /* [ 30] */
    CAN_DB_SIG_MMI_LCA_AudioWarning, /* [ 31] */
    CAN_DB_SIG_MMI_ePTRegencyLevRequest, /* [ 32] */
    CAN_DB_SIG_MMI_DM_SwitchModeSts, /* [ 33] */
    CAN_DB_SIG_MMI_RoadCameraWarning, /* [ 34] */
    CAN_DB_SIG_MMI_BCM_DchaChargehint, /* [ 35] */
    CAN_DB_SIG_MMI_RDiffLockReq, /* [ 36] */
    CAN_DB_SIG_MMI_NationalDrivingRank, /* [ 37] */
    CAN_DB_SIG_MMI_EnergySavingModeReq, /* [ 38] */
    CAN_DB_SIG_MMI_CampModeReq, /* [ 39] */
    CAN_DB_SIG_MMI_EpedalSettingInfo, /* [ 40] */
    CAN_DB_SIG_MMI_ESCoffInfo, /* [ 41] */
    CAN_DB_SIG_MMI_HDC_Request, /* [ 42] */
    CAN_DB_SIG_MMI_IntellTurnAidReq, /* [ 43] */
    CAN_DB_SIG_MMI_IntellTurnAidTerrSeln, /* [ 44] */
    CAN_DB_SIG_MMI_OnboardScaleReq, /* [ 45] */
    CAN_DB_SIG_MMI_iTPMS_reset_Request, /* [ 46] */
    CAN_DB_SIG_MMI_Nav_SpeedLimit, /* [ 47] */
    CAN_DB_SIG_MMI_Nav_RampSts, /* [ 48] */
    CAN_DB_SIG_MMI_Nav_CurrRoadType, /* [ 49] */
    CAN_DB_SIG_MMI_Nav_status, /* [ 50] */
    CAN_DB_SIG_MMI_Nav_CountryID, /* [ 51] */
    CAN_DB_SIG_MMI_TollGateIndication, /* [ 52] */
    CAN_DB_SIG_MMI_SVC_status, /* [ 53] */
    CAN_DB_SIG_MMI_APA_Function_Select, /* [ 54] */
    CAN_DB_SIG_MMI_SVA_Request, /* [ 55] */
    CAN_DB_SIG_MMI_APA_ConfirmButton, /* [ 56] */
    CAN_DB_SIG_MMI_PSC_Function_Select, /* [ 57] */
    CAN_DB_SIG_MMI_NavTunnelIndication, /* [ 58] */
    CAN_DB_SIG_MMI_NavDestinationIndication, /* [ 59] */
    CAN_DB_SIG_MMI_DayNightMode, /* [ 60] */
    CAN_DB_SIG_MMI_IBBrakeModeSet, /* [ 61] */
    CAN_DB_SIG_MMI_SailingSwitch, /* [ 62] */
    CAN_DB_SIG_MMI_Start_Stop_switch, /* [ 63] */
    CAN_DB_SIG_MMI_NavSyncDisplay, /* [ 64] */
    CAN_DB_SIG_MMI_Safety_Info_AliveCounter, /* [ 65] */
    CAN_DB_SIG_MMI_Safety_Info_CheckSum, /* [ 66] */
    CAN_DB_SIG_MMI_DchaChargeControlCmd, /* [ 67] */
    CAN_DB_SIG_MMI_SocWarValue, /* [ 68] */
    CAN_DB_SIG_MMI_EVDTEodometer_ModeSet, /* [ 69] */
    CAN_DB_SIG_MMI_FridgeCoolReq, /* [ 70] */
    CAN_DB_SIG_MMI_SaveModeReq, /* [ 71] */
    CAN_DB_SIG_MMI_ACDisChrgCmd, /* [ 72] */
    CAN_DB_SIG_MMI_RearPanelDisChrgCmd, /* [ 73] */
    CAN_DB_SIG_MMI_DCDisChrgCmd, /* [ 74] */
    CAN_DB_SIG_MMI_FrontPanelDisChrgCmd, /* [ 75] */
    CAN_DB_SIG_MMI_OTA_Status, /* [ 76] */
    CAN_DB_SIG_MMI_MidPanelDisChrgCmd, /* [ 77] */
    CAN_DB_SIG_MMI_RefuUnlckReq, /* [ 78] */
    CAN_DB_SIG_MMI_SOCPointSet, /* [ 79] */
    CAN_DB_SIG_EMS_ControlSetSpeed, /* [ 80] */
    CAN_DB_SIG_EMS_CruiseSwitchSts, /* [ 81] */
    CAN_DB_SIG_EMS_CruiseControlSts, /* [ 82] */
    CAN_DB_SIG_EMS_Real_PedalPositionInvalid, /* [ 83] */
    CAN_DB_SIG_EMS_Real_PedalPosition, /* [ 84] */
    CAN_DB_SIG_EMS_FuelPulsesRollingCounter, /* [ 85] */
    CAN_DB_SIG_EMS_EngineSpeedRPM, /* [ 86] */
    CAN_DB_SIG_EMS_EngineSpeedRPMInvalid, /* [ 87] */
    CAN_DB_SIG_EMS_EngStatus, /* [ 88] */
    CAN_DB_SIG_EMS_AccelPedalPosition, /* [ 89] */
    CAN_DB_SIG_EMS_AccelPedalPositionInvalid, /* [ 90] */
    CAN_DB_SIG_EMS_EngineCoolantTemperature, /* [ 91] */
    CAN_DB_SIG_EMS_EngineCoolantTemperatureInva, /* [ 92] */
    CAN_DB_SIG_EMS_EngineSVSTelltale, /* [ 93] */
    CAN_DB_SIG_EMS_EngineMILTelltale, /* [ 94] */
    CAN_DB_SIG_EMS_OilPressureWarning, /* [ 95] */
    CAN_DB_SIG_EMS_Odometerbackup, /* [ 96] */
    CAN_DB_SIG_EMS_LIMSetSpeed, /* [ 97] */
    CAN_DB_SIG_EMS_EAV_ModSetStatus, /* [ 98] */
    CAN_DB_SIG_EMS_LIMControlSts, /* [ 99] */
    CAN_DB_SIG_EMS_LIMmemorySts_Reserved, /* [100] */
    CAN_DB_SIG_EMS_LIMSwitchSts, /* [101] */
    CAN_DB_SIG_EMS_LIMOverSpdWarningSts, /* [102] */
    CAN_DB_SIG_EMS_GPF_Warning, /* [103] */
    CAN_DB_SIG_EMS_BrakeOverrideSts, /* [104] */
    CAN_DB_SIG_EMS_TankLeakDiagSts, /* [105] */
    CAN_DB_SIG_EMS_AdaptiveTargetMode, /* [106] */
    CAN_DB_SIG_EMS_DM_ModeProgBar, /* [107] */
    CAN_DB_SIG_EGSM_ParkReq, /* [108] */
    CAN_DB_SIG_EGSM_DriveMod, /* [109] */
    CAN_DB_SIG_EGSM_LeverPosition, /* [110] */
    CAN_DB_SIG_EGSM_Paddleinputs, /* [111] */
    CAN_DB_SIG_EGSM_ReleaseReq, /* [112] */
    CAN_DB_SIG_EGSM_Status_AliveCounter, /* [113] */
    CAN_DB_SIG_EGSM_Status_Checksum, /* [114] */
    CAN_DB_SIG_ODP_OBC_ChrgrSt, /* [115] */
    CAN_DB_SIG_OBC_OnBdFailSt, /* [116] */
    CAN_DB_SIG_OBC_OnBdDisChrgrCCline_PHEV, /* [117] */
    CAN_DB_SIG_ODP_OBC_OnBdCCline, /* [118] */
    CAN_DB_SIG_ODP_OBC_OnBdCPline, /* [119] */
    CAN_DB_SIG_ODP_OBC_OnBdDisChrgrCCline_EV, /* [120] */
    CAN_DB_SIG_ODP_OBC_iInAct, /* [121] */
    CAN_DB_SIG_OBC_uInAct, /* [122] */
    CAN_DB_SIG_ODP_OBC_POuptAct, /* [123] */
    CAN_DB_SIG_ODP_OBC_Failmode_ACVI_overtemp, /* [124] */
    CAN_DB_SIG_ODP_OBC_Failmode_Hndl_Error, /* [125] */
    CAN_DB_SIG_ODP_OBC_Failmode_ACVI_Invalid, /* [126] */
    CAN_DB_SIG_BMSH_BattSOH, /* [127] */
    CAN_DB_SIG_BMSH_ChgTimeRemain, /* [128] */
    CAN_DB_SIG_BMSH_BattRemainEnergy, /* [129] */
    CAN_DB_SIG_BMSH_Discharge_Over_Current, /* [130] */
    CAN_DB_SIG_BMSH_ThermalOutofControl, /* [131] */
    CAN_DB_SIG_BMSH_BattTempAvg, /* [132] */
    CAN_DB_SIG_BMSH_TempSensor_MinTemp, /* [133] */
    CAN_DB_SIG_VCU_ePTModeSelect, /* [134] */
    CAN_DB_SIG_VCU_ePTModeActual, /* [135] */
    CAN_DB_SIG_VCU_Warning_IMMO_Fail, /* [136] */
    CAN_DB_SIG_VCU_ChargerFault, /* [137] */
    CAN_DB_SIG_VCU_ePTReady, /* [138] */
    CAN_DB_SIG_VCU_ePTDivPowerPcent, /* [139] */
    CAN_DB_SIG_VCU_ePTReleaseSig, /* [140] */
    CAN_DB_SIG_VCU_ePTRegencyLevInd, /* [141] */
    CAN_DB_SIG_VCU_ePTModReqRejt, /* [142] */
    CAN_DB_SIG_VCU_LimpHomeSts_HB, /* [143] */
    CAN_DB_SIG_VCU_TurtleLampOn, /* [144] */
    CAN_DB_SIG_VCU_ePTFault, /* [145] */
    CAN_DB_SIG_VCU_EVDTEodometer, /* [146] */
    CAN_DB_SIG_HmiEngHybSts, /* [147] */
    CAN_DB_SIG_VCU_PtModAct, /* [148] */
    CAN_DB_SIG_VCU_PtModBlkd, /* [149] */
    CAN_DB_SIG_VCU_PwrLoIndcn, /* [150] */
    CAN_DB_SIG_VCU_EngFltIndcn, /* [151] */
    CAN_DB_SIG_VCU_VehPullOverWarn, /* [152] */
    CAN_DB_SIG_VCU_EpedalActive, /* [153] */
    CAN_DB_SIG_VCU_MainDrivingDoorOpenHV, /* [154] */
    CAN_DB_SIG_DispWhlMotSysPrpsnMod, /* [155] */
    CAN_DB_SIG_VCU_DriverRemind, /* [156] */
    CAN_DB_SIG_VCU_DiscrgPanellSw, /* [157] */
    CAN_DB_SIG_VCU_DischgFailSt, /* [158] */
    CAN_DB_SIG_VCU_MileageReward, /* [159] */
    CAN_DB_SIG_DispOfPrpsnMod, /* [160] */
    CAN_DB_SIG_VCU_StartActive, /* [161] */
    CAN_DB_SIG_VCU_CruiseControlSts, /* [162] */
    CAN_DB_SIG_VCU_CruiseSwitchSts, /* [163] */
    CAN_DB_SIG_VCU_ControlSetSpeed, /* [164] */
    CAN_DB_SIG_VCU_DM_FailureReasonAndSysFaultF, /* [165] */
    CAN_DB_SIG_VCU_Real_PedalPosition, /* [166] */
    CAN_DB_SIG_VCU_ModeGearDisplaySts, /* [167] */
    CAN_DB_SIG_VCU_LIMOverSpdWarningSts, /* [168] */
    CAN_DB_SIG_VCU_EVSpeedlimitedInf, /* [169] */
    CAN_DB_SIG_VCU_ChargeHV_Status, /* [170] */
    CAN_DB_SIG_VCU_WhlDrvSt_CS, /* [171] */
    CAN_DB_SIG_VCU_LIMSetSpeed, /* [172] */
    CAN_DB_SIG_VCU_LIMSwitchSts, /* [173] */
    CAN_DB_SIG_VCU_LIMControlSts, /* [174] */
    CAN_DB_SIG_IPU_IsgTqActIsgTqAct, /* [175] */
    CAN_DB_SIG_IPU_IsgSpdActSgn, /* [176] */
    CAN_DB_SIG_IPU_TrqSpd_AliveCounter, /* [177] */
    CAN_DB_SIG_IPU_TrqSpd_Checksum, /* [178] */
    CAN_DB_SIG_IPU_TqAvlIsgMax, /* [179] */
    CAN_DB_SIG_IPU_TqAvlIsgMin, /* [180] */
    CAN_DB_SIG_IPU_Sts_AliveCounter, /* [181] */
    CAN_DB_SIG_IPU_Sts_Checksum, /* [182] */
    CAN_DB_SIG_AVAS_AVASDisabledSts, /* [183] */
    CAN_DB_SIG_AVAS_AVASBackwardDisabledSts, /* [184] */
    CAN_DB_SIG_AVAS_AVASforwardDisabledSts, /* [185] */
    CAN_DB_SIG_AVAS_AVASForwardWarningSts, /* [186] */
    CAN_DB_SIG_AVAS_AVASVolumeSts, /* [187] */
    CAN_DB_SIG_AVAS_AVASBackwardWarningSts, /* [188] */
    CAN_DB_SIG_ACU_DrvSeatbeltBucklestatus, /* [189] */
    CAN_DB_SIG_ACU_PassSeatbeWarning, /* [190] */
    CAN_DB_SIG_ACU_PassSeatOccupantSensorStat, /* [191] */
    CAN_DB_SIG_ACU_2nd_RSeatbeltBucklestatus, /* [192] */
    CAN_DB_SIG_ACU_PassengerAirbagStatus, /* [193] */
    CAN_DB_SIG_ACU_AirbagWarningStatus, /* [194] */
    CAN_DB_SIG_ACU_DrvSeatbeltBuckleInvalid, /* [195] */
    CAN_DB_SIG_ACU_PassSeatbeltBuckleInvalid, /* [196] */
    CAN_DB_SIG_ACU_2nd_LSeatbeltBucklestatus, /* [197] */
    CAN_DB_SIG_ACU_2nd_MSeatbeltBucklestatus, /* [198] */
    CAN_DB_SIG_ACU_3rd_LSeatbeltBucklestatus, /* [199] */
    CAN_DB_SIG_ACU_3rd_RSeatbeltBucklestatus, /* [200] */
    CAN_DB_SIG_ACU_3rd_MSeatbeltBucklestatus, /* [201] */
    CAN_DB_SIG_EPS_EpasFailed, /* [202] */
    CAN_DB_SIG_EPS_ModSetInhibit, /* [203] */
    CAN_DB_SIG_EPS_ModSts, /* [204] */
    CAN_DB_SIG_ESC_BrakePedalSwitchStatus, /* [205] */
    CAN_DB_SIG_ESC_EBDFailed, /* [206] */
    CAN_DB_SIG_ESC_ABSFailed, /* [207] */
    CAN_DB_SIG_ESC_TCSFailed, /* [208] */
    CAN_DB_SIG_ESC_ESPFailed, /* [209] */
    CAN_DB_SIG_ESC_VehicleSpeed, /* [210] */
    CAN_DB_SIG_ESC_PATAResponse, /* [211] */
    CAN_DB_SIG_ESC_LampInfo, /* [212] */
    CAN_DB_SIG_ESC_VehicleSpeedInvalid, /* [213] */
    CAN_DB_SIG_ESC_AVHStatus, /* [214] */
    CAN_DB_SIG_ESC_EPBStatus, /* [215] */
    CAN_DB_SIG_ESC_EPBErrorStatus, /* [216] */
    CAN_DB_SIG_ESC_BrakePedalSwitchInvalid, /* [217] */
    CAN_DB_SIG_ESC_HHC_ErrorStatus, /* [218] */
    CAN_DB_SIG_ESC_HDC_ErrorStatus, /* [219] */
    CAN_DB_SIG_ESC_HDC_Active, /* [220] */
    CAN_DB_SIG_ESC_AVH_Disp_WithoutSeatbelt, /* [221] */
    CAN_DB_SIG_ESC_ParkingBrakeFail, /* [222] */
    CAN_DB_SIG_ESC_EPB_Disp_WithoutSeatbelt, /* [223] */
    CAN_DB_SIG_ESC_EPB_Disp_WithoutBrake, /* [224] */
    CAN_DB_SIG_ESC_EPB_SlopeOverThresholdRemind, /* [225] */
    CAN_DB_SIG_ESC_EPB_ReleaseInNonP, /* [226] */
    CAN_DB_SIG_ESC_HDC_Disp_DiscTempHigh, /* [227] */
    CAN_DB_SIG_ESC_HDC_TargetSpeed, /* [228] */
    CAN_DB_SIG_ESC_SystemWarning, /* [229] */
    CAN_DB_SIG_ESC_iTPMS_FLTyreWarn, /* [230] */
    CAN_DB_SIG_ESC_iTPMS_FRTyreWarn, /* [231] */
    CAN_DB_SIG_ESC_iTPMS_RLTyreWarn, /* [232] */
    CAN_DB_SIG_ESC_iTPMS_RRTyreWarn, /* [233] */
    CAN_DB_SIG_ESC_iTPMS_comTyreWarn, /* [234] */
    CAN_DB_SIG_ESC_iTPMS_SystemSt, /* [235] */
    CAN_DB_SIG_ESC_iTPMSCalPsbl, /* [236] */
    CAN_DB_SIG_ESC_iTPMSCalsts, /* [237] */
    CAN_DB_SIG_ESC_BrakeFluidLevelLow, /* [238] */
    CAN_DB_SIG_ESC_MbRegenTargetWheelSts, /* [239] */
    CAN_DB_SIG_RSRSR_SystemStatus, /* [240] */
    CAN_DB_SIG_RSRSR_LCA_Status, /* [241] */
    CAN_DB_SIG_RSRSR_RCTA_Status, /* [242] */
    CAN_DB_SIG_RSRSR_RCW_Status, /* [243] */
    CAN_DB_SIG_RSRSR_LCA_WarningLeft, /* [244] */
    CAN_DB_SIG_RSRSR_LCA_WarningRight, /* [245] */
    CAN_DB_SIG_RSRSR_RCTA_WarningLeft, /* [246] */
    CAN_DB_SIG_RSRSR_RCW_Warning, /* [247] */
    CAN_DB_SIG_RSRSR_DOW_Status, /* [248] */
    CAN_DB_SIG_RSRSR_DOW_WarningLeft, /* [249] */
    CAN_DB_SIG_RSRSR_DOW_WarningRight, /* [250] */
    CAN_DB_SIG_RSRSR_LCA_AudioSwitch, /* [251] */
    CAN_DB_SIG_RSRSR_RCTA_WarningRight, /* [252] */
    CAN_DB_SIG_RSRSR_RCTA_Brake, /* [253] */
    CAN_DB_SIG_RSRSR_RCW_Brake, /* [254] */
    CAN_DB_SIG_FCS_ALAD_SwitchStatus, /* [255] */
    CAN_DB_SIG_FCS_ALAD_Type, /* [256] */
    CAN_DB_SIG_FCS_ALAD_WarningType, /* [257] */
    CAN_DB_SIG_FCS_ALAD_Status, /* [258] */
    CAN_DB_SIG_FCS_FCS_Status, /* [259] */
    CAN_DB_SIG_FCS_ALAD_Warning, /* [260] */
    CAN_DB_SIG_FCS_IHBC_Status, /* [261] */
    CAN_DB_SIG_FCS_IHBC_LightDistribReq, /* [262] */
    CAN_DB_SIG_FCS_IHBC_Switch, /* [263] */
    CAN_DB_SIG_FCS_SLIF_Switch, /* [264] */
    CAN_DB_SIG_FCS_Sign_Speedlimit, /* [265] */
    CAN_DB_SIG_FCS_Sign_SpeedLimitCancelled, /* [266] */
    CAN_DB_SIG_FCS_DrvOff_Switch, /* [267] */
    CAN_DB_SIG_FCS_SLIF_Status, /* [268] */
    CAN_DB_SIG_FCS_SLIF_Warning, /* [269] */
    CAN_DB_SIG_FCS_SLIF_WarningSwitch, /* [270] */
    CAN_DB_SIG_FCS_Sign_Misc, /* [271] */
    CAN_DB_SIG_FCS_SLIF_IHBC_Status_AliveCounte, /* [272] */
    CAN_DB_SIG_FCS_SLIF_MiscSts, /* [273] */
    CAN_DB_SIG_FCS_SLIF_IHBC_Status_CheckSum, /* [274] */
    CAN_DB_SIG_FCS_LineLeft_D, /* [275] */
    CAN_DB_SIG_FCS_LineLeft_Type, /* [276] */
    CAN_DB_SIG_FCS_LineLeft_Warning, /* [277] */
    CAN_DB_SIG_FCS_LineLeft_Color, /* [278] */
    CAN_DB_SIG_FCS_LineRight_Color, /* [279] */
    CAN_DB_SIG_FCS_LineRight_Warning, /* [280] */
    CAN_DB_SIG_FCS_LineRight_D, /* [281] */
    CAN_DB_SIG_FCS_LineRight_Type, /* [282] */
    CAN_DB_SIG_FCS_Lane_Radius, /* [283] */
    CAN_DB_SIG_FCS_DriveOnLine, /* [284] */
    CAN_DB_SIG_FCS_LaneChange_Det, /* [285] */
    CAN_DB_SIG_FCS_LaneCenter_Color, /* [286] */
    CAN_DB_SIG_FCS_ELK_SwitchStatus, /* [287] */
    CAN_DB_SIG_FCS_ELK_Status, /* [288] */
    CAN_DB_SIG_FCS_ELK_LeftMode, /* [289] */
    CAN_DB_SIG_FCS_ELK_RightMode, /* [290] */
    CAN_DB_SIG_FCS_AEB_DecCtrlACT, /* [291] */
    CAN_DB_SIG_FCS_AEB_WarningType, /* [292] */
    CAN_DB_SIG_FCS_AEB_Switch, /* [293] */
    CAN_DB_SIG_FCS_AEB_Status, /* [294] */
    CAN_DB_SIG_FCS_AEB_Warning, /* [295] */
    CAN_DB_SIG_FCS_AEB_FCWSenlevel, /* [296] */
    CAN_DB_SIG_FCS_ALOD_SpeedSetDisp, /* [297] */
    CAN_DB_SIG_FCS_ALOD_TimeGap, /* [298] */
    CAN_DB_SIG_FCS_ALOD_TimeGapDisp, /* [299] */
    CAN_DB_SIG_FCS_ALOD_Status, /* [300] */
    CAN_DB_SIG_FCS_ALOD_ControlType, /* [301] */
    CAN_DB_SIG_FCS_ALOD_Warning, /* [302] */
    CAN_DB_SIG_FCS_FRS_Status, /* [303] */
    CAN_DB_SIG_FCS_ALOD_Info, /* [304] */
    CAN_DB_SIG_FCS_Display_AliveCounter, /* [305] */
    CAN_DB_SIG_FCS_Display_CheckSum, /* [306] */
    CAN_DB_SIG_FCS_ObjFront1_Dx, /* [307] */
    CAN_DB_SIG_FCS_ObjFront1_Dy, /* [308] */
    CAN_DB_SIG_FCS_ObjFront1_Type, /* [309] */
    CAN_DB_SIG_FCS_ObjFront1_Color, /* [310] */
    CAN_DB_SIG_FCS_ObjFront1_Warning, /* [311] */
    CAN_DB_SIG_FCS_ObjFront2_Dx, /* [312] */
    CAN_DB_SIG_FCS_ObjFront2_Dy, /* [313] */
    CAN_DB_SIG_FCS_ObjFront2_Type, /* [314] */
    CAN_DB_SIG_FCS_ObjFront2_Color, /* [315] */
    CAN_DB_SIG_FCS_ObjFront1_Heading, /* [316] */
    CAN_DB_SIG_FCS_ObjFront2_Heading, /* [317] */
    CAN_DB_SIG_FCS_ObjFrontLeft_Dx, /* [318] */
    CAN_DB_SIG_FCS_ObjFrontLeft_Dy, /* [319] */
    CAN_DB_SIG_FCS_ObjFrontLeft_Type, /* [320] */
    CAN_DB_SIG_FCS_ObjFrontLeft_Color, /* [321] */
    CAN_DB_SIG_FCS_ObjFrontRight_Dx, /* [322] */
    CAN_DB_SIG_FCS_ObjFrontRight_Dy, /* [323] */
    CAN_DB_SIG_FCS_ObjFrontRight_Type, /* [324] */
    CAN_DB_SIG_FCS_ObjFrontRight_Color, /* [325] */
    CAN_DB_SIG_FCS_ObjFrontLeft_Heading, /* [326] */
    CAN_DB_SIG_FCS_ObjFrontRight_Heading, /* [327] */
    CAN_DB_SIG_AC_ACCompReq, /* [328] */
    CAN_DB_SIG_AC_AmbientTemperatureInvalid, /* [329] */
    CAN_DB_SIG_AC_InsideTemperatureInvalid, /* [330] */
    CAN_DB_SIG_AC_AmbientTemperature, /* [331] */
    CAN_DB_SIG_AC_PM25InDen, /* [332] */
    CAN_DB_SIG_AC_PM25OutDen, /* [333] */
    CAN_DB_SIG_AC_AirInQLevel, /* [334] */
    CAN_DB_SIG_AC_AirOutQLevel, /* [335] */
    CAN_DB_SIG_AC_PM25Sts, /* [336] */
    CAN_DB_SIG_AC_InsideTemperature, /* [337] */
    CAN_DB_SIG_AC_ParkingClimateStatus, /* [338] */
    CAN_DB_SIG_AC_ParkingClimateFailStatus, /* [339] */
    CAN_DB_SIG_AC_PM25PopupReq, /* [340] */
    CAN_DB_SIG_TPMS_FLTyrePr, /* [341] */
    CAN_DB_SIG_TPMS_FRTyrePr, /* [342] */
    CAN_DB_SIG_TPMS_RLTyrePr, /* [343] */
    CAN_DB_SIG_TPMS_RRTyrePr, /* [344] */
    CAN_DB_SIG_TPMS_FLTyreTemp, /* [345] */
    CAN_DB_SIG_TPMS_FRTyreTemp, /* [346] */
    CAN_DB_SIG_TPMS_RLTyreTemp, /* [347] */
    CAN_DB_SIG_TPMS_RRTyreTemp, /* [348] */
    CAN_DB_SIG_TPMS_FL_Learning_Sts, /* [349] */
    CAN_DB_SIG_TPMS_FR_Learning_Sts, /* [350] */
    CAN_DB_SIG_TPMS_RL_Learning_Sts, /* [351] */
    CAN_DB_SIG_TPMS_RR_Learning_Sts, /* [352] */
    CAN_DB_SIG_TPMS_Mode, /* [353] */
    CAN_DB_SIG_TPMS_W_SensorVoltageFL, /* [354] */
    CAN_DB_SIG_TPMS_W_SensorVoltageFR, /* [355] */
    CAN_DB_SIG_TPMS_W_SensorVoltageRL, /* [356] */
    CAN_DB_SIG_TPMS_W_SensorVoltageRR, /* [357] */
    CAN_DB_SIG_BCM_TurnIndicatorLeft, /* [358] */
    CAN_DB_SIG_BCM_AntiPinchWarnSetResp, /* [359] */
    CAN_DB_SIG_BCM_TurnIndicatorRight, /* [360] */
    CAN_DB_SIG_BCM_TurnLeverSts, /* [361] */
    CAN_DB_SIG_BCM_LowBeamSts, /* [362] */
    CAN_DB_SIG_BCM_HighBeamSts, /* [363] */
    CAN_DB_SIG_BCM_PositionLightSts, /* [364] */
    CAN_DB_SIG_BCM_DayRunningLightSts, /* [365] */
    CAN_DB_SIG_BCM_FollowMeHomeActive, /* [366] */
    CAN_DB_SIG_BCM_FrontFogLightSts, /* [367] */
    CAN_DB_SIG_BCM_RearFogLightSts, /* [368] */
    CAN_DB_SIG_BCM_LightLeftOn, /* [369] */
    CAN_DB_SIG_BCM_Warning_RKE_LOW_BATT, /* [370] */
    CAN_DB_SIG_BCM_BrakeLampsFailure, /* [371] */
    CAN_DB_SIG_BCM_PositionLampsFailure, /* [372] */
    CAN_DB_SIG_BCM_ReverseLampsFailure, /* [373] */
    CAN_DB_SIG_BCM_RrFogLampsFailure, /* [374] */
    CAN_DB_SIG_BCM_DI_LampsFailure, /* [375] */
    CAN_DB_SIG_BCM_LowBeamLampsFailure, /* [376] */
    CAN_DB_SIG_BCM_Drv_Wdw_valid, /* [377] */
    CAN_DB_SIG_BCM_Drv_Val_Wdw_Opened, /* [378] */
    CAN_DB_SIG_BCM_Drv_Wdw_OD_Sts, /* [379] */
    CAN_DB_SIG_BCM_Drv_Wdw_Obs_InhibitSts, /* [380] */
    CAN_DB_SIG_BCM_Drv_Wdw_Running_Sts, /* [381] */
    CAN_DB_SIG_BCM_Drv_Wdw_PositionSts, /* [382] */
    CAN_DB_SIG_BCM_Drv_Wdw_Error, /* [383] */
    CAN_DB_SIG_BCM_RLD_Wdw_valid, /* [384] */
    CAN_DB_SIG_BCM_RLD_Val_Wdw_Opened, /* [385] */
    CAN_DB_SIG_BCM_RLD_Wdw_OD_Sts, /* [386] */
    CAN_DB_SIG_BCM_RLD_Wdw_Obs_InhibitSts, /* [387] */
    CAN_DB_SIG_BCM_RLD_Wdw_Running_Sts, /* [388] */
    CAN_DB_SIG_BCM_RLD_Wdw_PositionSts, /* [389] */
    CAN_DB_SIG_BCM_RLD_Wdw_Error, /* [390] */
    CAN_DB_SIG_BCM_FrontLeftDoorAjarStatus, /* [391] */
    CAN_DB_SIG_BCM_RearLeftDoorAjarStatus, /* [392] */
    CAN_DB_SIG_BCM_MechaKey_LockAction, /* [393] */
    CAN_DB_SIG_BCM_WdwNotCloseWarning, /* [394] */
    CAN_DB_SIG_BCM_AutoLockFailWarning, /* [395] */
    CAN_DB_SIG_BCM_DoorChildLockst, /* [396] */
    CAN_DB_SIG_BCM_RearMirrorFoldSetResp, /* [397] */
    CAN_DB_SIG_BCM_DoorLockStatusRL, /* [398] */
    CAN_DB_SIG_BCM_DoorLockStatusDrv, /* [399] */
    CAN_DB_SIG_BCM_Pas_Wdw_valid, /* [400] */
    CAN_DB_SIG_BCM_Pas_Val_Wdw_Opened, /* [401] */
    CAN_DB_SIG_BCM_Pas_Wdw_OD_Sts, /* [402] */
    CAN_DB_SIG_BCM_Pas_Wdw_Obs_InhibitSts, /* [403] */
    CAN_DB_SIG_BCM_Pas_Wdw_Running_Sts, /* [404] */
    CAN_DB_SIG_BCM_Pas_Wdw_PositionSts, /* [405] */
    CAN_DB_SIG_BCM_Pas_Wdw_Error, /* [406] */
    CAN_DB_SIG_BCM_RRD_Wdw_valid, /* [407] */
    CAN_DB_SIG_BCM_RRD_Val_Wdw_Opened, /* [408] */
    CAN_DB_SIG_BCM_RRD_Wdw_OD_Sts, /* [409] */
    CAN_DB_SIG_BCM_RRD_Wdw_Obs_InhibitSts, /* [410] */
    CAN_DB_SIG_BCM_RRD_Wdw_Running_Sts, /* [411] */
    CAN_DB_SIG_BCM_RRD_Wdw_PositionSts, /* [412] */
    CAN_DB_SIG_BCM_RRD_Wdw_Error, /* [413] */
    CAN_DB_SIG_BCM_FrontRightDoorAjarStatus, /* [414] */
    CAN_DB_SIG_BCM_RearRightDoorAjarStatus, /* [415] */
    CAN_DB_SIG_BCM_CargoBoxLightSts, /* [416] */
    CAN_DB_SIG_BCM_FueltankCapSts, /* [417] */
    CAN_DB_SIG_BCM_DoorLockStatusRR, /* [418] */
    CAN_DB_SIG_BCM_DoorLockStatusPass, /* [419] */
    CAN_DB_SIG_BCM_RearDefrosterSts, /* [420] */
    CAN_DB_SIG_BCM_Central_Lock_CMD, /* [421] */
    CAN_DB_SIG_BCM_Central_unLock_CMD, /* [422] */
    CAN_DB_SIG_BCM_HoodAjarStatus, /* [423] */
    CAN_DB_SIG_BCM_TrunkAjarStatus, /* [424] */
    CAN_DB_SIG_BCM_RainshedStatus, /* [425] */
    CAN_DB_SIG_BCM_FollowMeHomeTimeSelectResp, /* [426] */
    CAN_DB_SIG_BCM_RearLightHardSwtSts, /* [427] */
    CAN_DB_SIG_BCM_AutoCloseWindowSetResp, /* [428] */
    CAN_DB_SIG_BCM_RKEUnlockSetResp, /* [429] */
    CAN_DB_SIG_BCM_KeyInwithDrvDoorAjar, /* [430] */
    CAN_DB_SIG_BCM_ATWS_St, /* [431] */
    CAN_DB_SIG_BCM_RLSModeSts, /* [432] */
    CAN_DB_SIG_BCM_IndicationPressClutch, /* [433] */
    CAN_DB_SIG_BCM_DM_ReqType, /* [434] */
    CAN_DB_SIG_BCM_ATWarnTypeSetResp, /* [435] */
    CAN_DB_SIG_BCM_DayRunLightSetResp, /* [436] */
    CAN_DB_SIG_BCM_RearWiperAutoActiveAtReverse, /* [437] */
    CAN_DB_SIG_BCM_ReverseGearInfo, /* [438] */
    CAN_DB_SIG_BCM_PowerMode, /* [439] */
    CAN_DB_SIG_BCM_PowertrainChainStatus, /* [440] */
    CAN_DB_SIG_BCM_Warning_IMMO_Fail, /* [441] */
    CAN_DB_SIG_BCM_RLS_WinCloseReminder, /* [442] */
    CAN_DB_SIG_BCM_360LtgExecuteStsFB, /* [443] */
    CAN_DB_SIG_BCM_360LtgExecuteZoneFB, /* [444] */
    CAN_DB_SIG_BCM_RKE_RemoteACCtrl, /* [445] */
    CAN_DB_SIG_BCM_Odometerbackup, /* [446] */
    CAN_DB_SIG_BCM_BottomClutchSwitchInvalid, /* [447] */
    CAN_DB_SIG_L_Sunroof_Operation_State, /* [448] */
    CAN_DB_SIG_BCM_sunroof_valid, /* [449] */
    CAN_DB_SIG_L_sunroof_Val_Opened, /* [450] */
    CAN_DB_SIG_L_sunroof_ap_event, /* [451] */
    CAN_DB_SIG_BCM_sunroof_Error, /* [452] */
    CAN_DB_SIG_L_Sunroof_Position, /* [453] */
    CAN_DB_SIG_PEPS_RKECommand, /* [454] */
    CAN_DB_SIG_PEPS_Warning_Stop_Emergency, /* [455] */
    CAN_DB_SIG_PEPS_Warning_Stop_Moving, /* [456] */
    CAN_DB_SIG_PEPS_PowerModeValidity, /* [457] */
    CAN_DB_SIG_PEPS_PowerMode, /* [458] */
    CAN_DB_SIG_PEPS_EngineforbidSt, /* [459] */
    CAN_DB_SIG_PEPS_EngForbidWarn, /* [460] */
    CAN_DB_SIG_PEPS_RemoteControlSt, /* [461] */
    CAN_DB_SIG_PEPS_FailReason2TBOX, /* [462] */
    CAN_DB_SIG_PEPS_StatusResponse2TBOX, /* [463] */
    CAN_DB_SIG_PEPS_Warning_No_key_found, /* [464] */
    CAN_DB_SIG_PEPS_Indication_press_brake_clut, /* [465] */
    CAN_DB_SIG_PEPS_Indication_shift_to_PN, /* [466] */
    CAN_DB_SIG_PEPS_TrunkUnlock_Enable, /* [467] */
    CAN_DB_SIG_PEPS_Indication_shift_to_Park, /* [468] */
    CAN_DB_SIG_PEPS_Warning_keyInReminder, /* [469] */
    CAN_DB_SIG_PEPS_IGN1FailureWarning, /* [470] */
    CAN_DB_SIG_PEPS_Warning_Auth_ESCL_Fail, /* [471] */
    CAN_DB_SIG_PEPS_Warning_UID_LOW_BATT, /* [472] */
    CAN_DB_SIG_PEPS_ChargerConnectStarter_Warnn, /* [473] */
    CAN_DB_SIG_PEPS_Warning_IMMO_Fail, /* [474] */
    CAN_DB_SIG_PEPS_TELAuthenStatus, /* [475] */
    CAN_DB_SIG_PEPS_Indication_UID_Closer, /* [476] */
    CAN_DB_SIG_PEPS_CrankAllowSts, /* [477] */
    CAN_DB_SIG_PEPS_Warning_PoweOnCounterRemain, /* [478] */
    CAN_DB_SIG_PEPS_0x1E2_TimeoutFlag, /* [479] */
    CAN_DB_SIG_PEPS_0x270_TimeoutFlag, /* [480] */
    CAN_DB_SIG_PEPS_0x272_TimeoutFlag, /* [481] */
    CAN_DB_SIG_PEPS_SSB_Failure_warning, /* [482] */
    CAN_DB_SIG_PEPS_WelcomeLightSetResp, /* [483] */
    CAN_DB_SIG_PEPS_APUCfgResult, /* [484] */
    CAN_DB_SIG_PEPS_WALCfgResult, /* [485] */
    CAN_DB_SIG_TPMS_FLTyreWarn, /* [486] */
    CAN_DB_SIG_TPMS_FLTyre_Temperature, /* [487] */
    CAN_DB_SIG_TPMS_FLTyre_Fast_Leak, /* [488] */
    CAN_DB_SIG_TPMS_FLTyre_Sensor_Failure, /* [489] */
    CAN_DB_SIG_TPMS_0x1F1_TimeoutFlag, /* [490] */
    CAN_DB_SIG_TPMS_FRTyreWarn, /* [491] */
    CAN_DB_SIG_TPMS_FRTyre_Temperature, /* [492] */
    CAN_DB_SIG_TPMS_FRTyre_Fast_Leak, /* [493] */
    CAN_DB_SIG_TPMS_FRTyre_Sensor_Failure, /* [494] */
    CAN_DB_SIG_BCM_DMSDriveModeReqRej, /* [495] */
    CAN_DB_SIG_TPMS_RLTyreWarn, /* [496] */
    CAN_DB_SIG_TPMS_RLTyre_Temperature, /* [497] */
    CAN_DB_SIG_TPMS_RLTyre_Fast_Leak, /* [498] */
    CAN_DB_SIG_TPMS_RLTyre_Sensor_Failure, /* [499] */
    CAN_DB_SIG_TPMS_RRTyreWarn, /* [500] */
    CAN_DB_SIG_TPMS_RRTyre_Temperature, /* [501] */
    CAN_DB_SIG_TPMS_RRTyre_Fast_Leak, /* [502] */
    CAN_DB_SIG_TPMS_RRTyre_Sensor_Failure, /* [503] */
    CAN_DB_SIG_TPMS_SystemSt, /* [504] */
    CAN_DB_SIG_BCM_DM_TargetModeReq, /* [505] */
    CAN_DB_SIG_BCM_DM_SwitchModeSts, /* [506] */
    CAN_DB_SIG_BCM_DMSVehicleMode, /* [507] */
    CAN_DB_SIG_BCM_DM_ChangeModeFailureControll, /* [508] */
    CAN_DB_SIG_BCM_DM_ChangeModeFailureReason, /* [509] */
    CAN_DB_SIG_BCM_0x283_TimeoutFlag, /* [510] */
    CAN_DB_SIG_BCM_DM_SwitchModeStsDisp, /* [511] */
    CAN_DB_SIG_VCU_SOCpointSetsts, /* [512] */
    CAN_DB_SIG_VCU_IntellTurnAidResp, /* [513] */
    CAN_DB_SIG_VCU_IntellTurnAidOprNtc, /* [514] */
    CAN_DB_SIG_VCU_IntellTurnAidOprGuide, /* [515] */
    CAN_DB_SIG_VCU_IntellTurnAidSts, /* [516] */
    CAN_DB_SIG_VCU_DriverTqInfo_AliveCounter, /* [517] */
    CAN_DB_SIG_VCU_DriverTqInfo_Checksum, /* [518] */
    CAN_DB_SIG_BMSH_stMode, /* [519] */
    CAN_DB_SIG_BMSH_VehicleHVILSts, /* [520] */
    CAN_DB_SIG_BMSH_InterHVILSts, /* [521] */
    CAN_DB_SIG_BMSH_InsulationSts, /* [522] */
    CAN_DB_SIG_BMSH_MainPrechgSt, /* [523] */
    CAN_DB_SIG_BMSH_BattCurr, /* [524] */
    CAN_DB_SIG_BMSH_HVBusVolt, /* [525] */
    CAN_DB_SIG_BMSH_BattVolt, /* [526] */
    CAN_DB_SIG_BMSH_BattFaultLampState, /* [527] */
    CAN_DB_SIG_BMSH_ChargeLEDCtrl, /* [528] */
    CAN_DB_SIG_BMSH_FastChgCC2ConntState, /* [529] */
    CAN_DB_SIG_DCChrgrSt, /* [530] */
    CAN_DB_SIG_BMSH_BattSOCDisp, /* [531] */
    CAN_DB_SIG_FuCnsAvgIndcdFuCnsIndcdVal1, /* [532] */
    CAN_DB_SIG_PwrCnsAvgIndcdPwrCns1, /* [533] */
    CAN_DB_SIG_PwrCnsAvgIndcdPwrCns2, /* [534] */
    CAN_DB_SIG_FuCnsAvgIndcdFuCnsIndcdVal2, /* [535] */
    CAN_DB_SIG_FuCnsAvgIndcdFuCnsIndcdVal3, /* [536] */
    CAN_DB_SIG_PwrCnsAvgIndcdPwrCns3, /* [537] */
    CAN_DB_SIG_EgyAvgCnsDstSg, /* [538] */
    CAN_DB_SIG_DstToEmptyIndcdDstToEmpty1, /* [539] */
    CAN_DB_SIG_AcEgyDistbn, /* [540] */
    CAN_DB_SIG_DstToEmptyIndcdDstToEmpty2, /* [541] */
    CAN_DB_SIG_TotDrvPwrAct, /* [542] */
    CAN_DB_SIG_ThmEgyDistbn, /* [543] */
    CAN_DB_SIG_HvConvPwrAct, /* [544] */
    CAN_DB_SIG_IdleChrgFctSts, /* [545] */
    CAN_DB_SIG_EVBlkd, /* [546] */
    CAN_DB_SIG_REVBlkd, /* [547] */
    CAN_DB_SIG_DispIdlChrgPwr, /* [548] */
    CAN_DB_SIG_DstEstimdToEmptyForDrvgElec, /* [549] */
    CAN_DB_SIG_DstEstimdToEmptyForDrvgElecPredT, /* [550] */
    CAN_DB_SIG_PCM_MotOverTemp, /* [551] */
    CAN_DB_SIG_PCM_IsgDeratSts, /* [552] */
    CAN_DB_SIG_PCM_MotTAlm, /* [553] */
    CAN_DB_SIG_PCM_IsgTAlm, /* [554] */
    CAN_DB_SIG_TrsmFltIndcn, /* [555] */
    CAN_DB_SIG_IPU_IsgOverTemp, /* [556] */
    CAN_DB_SIG_IPU_MotTAlm, /* [557] */
    CAN_DB_SIG_IPU_IPUTAlm, /* [558] */
    CAN_DB_SIG_IPU_IsgFAlm, /* [559] */
    CAN_DB_SIG_TRM_TurnLeftLampsFailure, /* [560] */
    CAN_DB_SIG_TRM_TurnRightLampsFailure, /* [561] */
    CAN_DB_SIG_TRM_EleIF_Connect_Status, /* [562] */
    CAN_DB_SIG_TRM_EleIF_Connect_Failure, /* [563] */
    CAN_DB_SIG_TRM_Message_AliveCounter, /* [564] */
    CAN_DB_SIG_TRM_Message_CheckSum, /* [565] */
    CAN_DB_SIG_IPK_SEND_E2_B7, /* [566] */
    CAN_DB_SIG_IPK_SEND_E2_B6, /* [567] */
    CAN_DB_SIG_IPK_SEND_E2_B5, /* [568] */
    CAN_DB_SIG_IPK_SEND_E2_B4, /* [569] */
    CAN_DB_SIG_IPK_SEND_E2_B3, /* [570] */
    CAN_DB_SIG_IPK_SEND_E2_B2, /* [571] */
    CAN_DB_SIG_IPK_SEND_E2_B1, /* [572] */
    CAN_DB_SIG_IPK_SEND_E2_B0, /* [573] */
    CAN_DB_SIG_IPK_IPKEngineTotalOdometer, /* [574] */
    CAN_DB_SIG_IPK_DayToEngSrv, /* [575] */
    CAN_DB_SIG_IPK_ServiceEngineMaintainInterva, /* [576] */
    CAN_DB_SIG_IPK_AirbagUnitLEDSts, /* [577] */
    CAN_DB_SIG_IPK_SVA_AudibleWarningCfgResult, /* [578] */
    CAN_DB_SIG_IPK_FuelLowLevelWarning, /* [579] */
    CAN_DB_SIG_IPK_ESCoffInfo, /* [580] */
    CAN_DB_SIG_IPK_Fail, /* [581] */
    CAN_DB_SIG_IPK_QDashALODFail, /* [582] */
    CAN_DB_SIG_IPK_FuelLevelSts, /* [583] */
    CAN_DB_SIG_IPK_AverageVehicleSpeed, /* [584] */
    CAN_DB_SIG_IPK_HandBrakeSts, /* [585] */
    CAN_DB_SIG_IPK_MaintanceWarningSts, /* [586] */
    CAN_DB_SIG_IPK_LanguageMode, /* [587] */
    CAN_DB_SIG_IPK_EPS_ModSetSelection, /* [588] */
    CAN_DB_SIG_IPK_EPS_DMCorrelativeMode, /* [589] */
    CAN_DB_SIG_IPK_Backlightadjust, /* [590] */
    CAN_DB_SIG_IPK_vDisplay, /* [591] */
    CAN_DB_SIG_IPK_OilLowPressure, /* [592] */
    CAN_DB_SIG_IPK_LIMmemoryEnabe_Reserved, /* [593] */
    CAN_DB_SIG_IPK_BattLowVoltageWarning, /* [594] */
    CAN_DB_SIG_IPK_driving_mode_light_sts, /* [595] */
    CAN_DB_SIG_IPK_AEB_FCWStateReq, /* [596] */
    CAN_DB_SIG_IPK_AEB_AEBStateReq, /* [597] */
    CAN_DB_SIG_IPK_ALOD_ControlTypeReq, /* [598] */
    CAN_DB_SIG_IPK_LCA_EnableStatus, /* [599] */
    CAN_DB_SIG_IPK_RCTA_EnableStatus, /* [600] */
    CAN_DB_SIG_IPK_RCW_EnableStatus, /* [601] */
    CAN_DB_SIG_IPK_AEB_FCWSenlevel, /* [602] */
    CAN_DB_SIG_IPK_LKS_LaneAssistTypeReq, /* [603] */
    CAN_DB_SIG_IPK_LDW_WarningTypeSetting, /* [604] */
    CAN_DB_SIG_IPK_IHBC_MenuReq, /* [605] */
    CAN_DB_SIG_IPK_SLIF_MenuReq, /* [606] */
    CAN_DB_SIG_FuFillgDetnForUseInt, /* [607] */
    CAN_DB_SIG_RstTrip1, /* [608] */
    CAN_DB_SIG_RstTrip2, /* [609] */
    CAN_DB_SIG_IPK_IPKTotalOdometer, /* [610] */
    CAN_DB_SIG_IPK_DTEodometer, /* [611] */
    CAN_DB_SIG_IPK_OdometerbackupEnable, /* [612] */
    CAN_DB_SIG_IPK_ServiceMaintainInterval, /* [613] */
    CAN_DB_SIG_IPK_Second, /* [614] */
    CAN_DB_SIG_IPK_Minute, /* [615] */
    CAN_DB_SIG_IPK_Hour, /* [616] */
    CAN_DB_SIG_IPK_TimeDisplayMode, /* [617] */
    CAN_DB_SIG_IPK_Day, /* [618] */
    CAN_DB_SIG_IPK_Month, /* [619] */
    CAN_DB_SIG_IPK_Year, /* [620] */
    CAN_DB_SIG_IPK_VehicleStopTime, /* [621] */
    CAN_DB_SIG_IPK_FuelSensorVoltage, /* [622] */
    CAN_DB_SIG_IPK_AverageFuelConsumptionOneCyc, /* [623] */
    CAN_DB_SIG_IPK_FuelSensorShortOrOpenBatt, /* [624] */
    CAN_DB_SIG_IPK_FuelSensorShortGND, /* [625] */
    CAN_DB_SIG_IPK_FuelSensorUpperLimit, /* [626] */
    CAN_DB_SIG_IPK_DayToSrv, /* [627] */
    CAN_DB_SIG_IPK_InstanteFuelConsumption, /* [628] */
    CAN_DB_SIG_IPK_Fuel_Info_AliveCounter, /* [629] */
    CAN_DB_SIG_IPK_Fuel_Info_Checksum, /* [630] */
    CAN_DB_SIG_IPK_EVDTEodometer, /* [631] */
    CAN_DB_SIG_IPK_AveragePowerConsumption, /* [632] */
    CAN_DB_SIG_IPK_InstantPowerConsumption, /* [633] */
    CAN_DB_SIG_IPK_AverageFuelConsumptionUnit, /* [634] */
    CAN_DB_SIG_IPK_AverageFuelConsumption, /* [635] */
    CAN_DB_SIG_IPK_Address, /* [636] */
    CAN_DB_SIG_IPK_RMR, /* [637] */
    CAN_DB_SIG_IPK_AWB, /* [638] */
    CAN_DB_SIG_IPK_Wakeup_reasons, /* [639] */
    CAN_DB_SIG_IPK_NMSts, /* [640] */
    CAN_DB_SIG_IPK_Stayawake_reasons, /* [641] */
    CAN_DB_SIG_MAX /* [total] end-of-enum sentinel */
} can_db_sig_id_t_ipk;

#define CAN_DB_IPK_MSG_COUNT  (75u)
#define CAN_DB_IPK_SIG_COUNT  (641u)
#define CAN_DB_IPK_RX_COUNT   (65u)
#define CAN_DB_IPK_TX_COUNT   (10u)

/* ---------------------------------------------------------------- */
/* RX timeout bitmap                                               */
/*                                                                 */
/* CAN_BITMAP_MAX is the width of the 3-slot timeout bitmap         */
/* (SIG_CAN_RX_TIMEOUT_MAP_{LO,HI,HI2}) and the SOC-facing        */
/* bit-N encoding.  Layout (per Sentinel strategy):                */
/*   bit  0..63  allocated to RX messages (DBC drives assignment)  */
/*   bit 64..95  reserved pool for future RX additions             */
/* A bit whose s_bit_to_can_id[] entry is 0 is a sentinel_unused   */
/* slot (historically mapped to a now-removed DBC message); it     */
/* is permanently 0 and never set by the timeout monitor.         */
/* ---------------------------------------------------------------- */
#define CAN_BITMAP_MAX          (96u)
#define CAN_BITMAP_RX_ALLOC_MAX (64u)  /* RX allocations cap (bit 0..63) */
#define sentinel_unused          (0u)

/* Per-bit CAN ID lookup table (Sentinel). */
/* Definition lives in can_db_<node>_gen.c; consumers */
/* include this header to get the prototype. */
extern const u32 s_bit_to_can_id[CAN_BITMAP_MAX];

#endif /* CAN_DB_IPK_GEN_H */
