/* AUTOGENERATED by tools/dbc_parse.py -- do not edit by hand. */
#ifndef CAN_DB_IPK_GEN_H
#define CAN_DB_IPK_GEN_H

#include <stdint.h>
#include "can_db_codec.h"

/* Signal IDs -- order matches can_sig_descs_ipk[] */
typedef enum {
    CAN_DB_SIG_INVALID = 0, /* [  0] invalid sentinel */
    CAN_DB_SIG_MMI_Second, /* [  1] */
    CAN_DB_SIG_MMI_Minute, /* [  2] */
    CAN_DB_SIG_MMI_Hour, /* [  3] */
    CAN_DB_SIG_MMI_Day, /* [  4] */
    CAN_DB_SIG_MMI_Month, /* [  5] */
    CAN_DB_SIG_MMI_Year, /* [  6] */
    CAN_DB_SIG_GPS_elevation_Info, /* [  7] */
    CAN_DB_SIG_MMI_GPS_Info5_AliveCounter, /* [  8] */
    CAN_DB_SIG_MMI_GPS_Info5_CheckSum, /* [  9] */
    CAN_DB_SIG_MMI_RightSwStatus, /* [ 10] */
    CAN_DB_SIG_MMI_LeftSwStatus, /* [ 11] */
    CAN_DB_SIG_MMI_UpSwStatus, /* [ 12] */
    CAN_DB_SIG_MMI_DownSwStatus, /* [ 13] */
    CAN_DB_SIG_MMI_ConfirmSwStatus, /* [ 14] */
    CAN_DB_SIG_MMI_ReturnSwStatus, /* [ 15] */
    CAN_DB_SIG_MMI_WorkMode, /* [ 16] */
    CAN_DB_SIG_MMI_SkinMode, /* [ 17] */
    CAN_DB_SIG_MMI_HUDAciveRequest, /* [ 18] */
    CAN_DB_SIG_MMI_AVH_Request, /* [ 19] */
    CAN_DB_SIG_MMI_OdometerClearReq, /* [ 20] */
    CAN_DB_SIG_MMI_SkinModeCorrelativeSts, /* [ 21] */
    CAN_DB_SIG_MMI_SVA_AudibleWarningOption, /* [ 22] */
    CAN_DB_SIG_MMI_LCA_AudioWarning, /* [ 23] */
    CAN_DB_SIG_MMI_ePTRegencyLevRequest, /* [ 24] */
    CAN_DB_SIG_MMI_DM_SwitchModeSts, /* [ 25] */
    CAN_DB_SIG_MMI_RoadCameraWarning, /* [ 26] */
    CAN_DB_SIG_MMI_BCM_DchaChargehint, /* [ 27] */
    CAN_DB_SIG_MMI_RDiffLockReq, /* [ 28] */
    CAN_DB_SIG_MMI_NationalDrivingRank, /* [ 29] */
    CAN_DB_SIG_MMI_EnergySavingModeReq, /* [ 30] */
    CAN_DB_SIG_MMI_CampModeReq, /* [ 31] */
    CAN_DB_SIG_MMI_EpedalSettingInfo, /* [ 32] */
    CAN_DB_SIG_MMI_ESCoffInfo, /* [ 33] */
    CAN_DB_SIG_MMI_HDC_Request, /* [ 34] */
    CAN_DB_SIG_MMI_IntellTurnAidReq, /* [ 35] */
    CAN_DB_SIG_MMI_IntellTurnAidTerrSeln, /* [ 36] */
    CAN_DB_SIG_MMI_OnboardScaleReq, /* [ 37] */
    CAN_DB_SIG_MMI_iTPMS_reset_Request, /* [ 38] */
    CAN_DB_SIG_MMI_Nav_SpeedLimit, /* [ 39] */
    CAN_DB_SIG_MMI_Nav_RampSts, /* [ 40] */
    CAN_DB_SIG_MMI_Nav_CurrRoadType, /* [ 41] */
    CAN_DB_SIG_MMI_Nav_status, /* [ 42] */
    CAN_DB_SIG_MMI_Nav_CountryID, /* [ 43] */
    CAN_DB_SIG_MMI_TollGateIndication, /* [ 44] */
    CAN_DB_SIG_MMI_SVC_status, /* [ 45] */
    CAN_DB_SIG_MMI_APA_Function_Select, /* [ 46] */
    CAN_DB_SIG_MMI_SVA_Request, /* [ 47] */
    CAN_DB_SIG_MMI_APA_ConfirmButton, /* [ 48] */
    CAN_DB_SIG_MMI_PSC_Function_Select, /* [ 49] */
    CAN_DB_SIG_MMI_NavTunnelIndication, /* [ 50] */
    CAN_DB_SIG_MMI_NavDestinationIndication, /* [ 51] */
    CAN_DB_SIG_MMI_DayNightMode, /* [ 52] */
    CAN_DB_SIG_MMI_IBBrakeModeSet, /* [ 53] */
    CAN_DB_SIG_MMI_SailingSwitch, /* [ 54] */
    CAN_DB_SIG_MMI_Start_Stop_switch, /* [ 55] */
    CAN_DB_SIG_MMI_NavSyncDisplay, /* [ 56] */
    CAN_DB_SIG_MMI_Safety_Info_AliveCounter, /* [ 57] */
    CAN_DB_SIG_MMI_Safety_Info_CheckSum, /* [ 58] */
    CAN_DB_SIG_MMI_DchaChargeControlCmd, /* [ 59] */
    CAN_DB_SIG_MMI_SocWarValue, /* [ 60] */
    CAN_DB_SIG_MMI_EVDTEodometer_ModeSet, /* [ 61] */
    CAN_DB_SIG_MMI_FridgeCoolReq, /* [ 62] */
    CAN_DB_SIG_MMI_SaveModeReq, /* [ 63] */
    CAN_DB_SIG_MMI_ACDisChrgCmd, /* [ 64] */
    CAN_DB_SIG_MMI_RearPanelDisChrgCmd, /* [ 65] */
    CAN_DB_SIG_MMI_DCDisChrgCmd, /* [ 66] */
    CAN_DB_SIG_MMI_FrontPanelDisChrgCmd, /* [ 67] */
    CAN_DB_SIG_MMI_OTA_Status, /* [ 68] */
    CAN_DB_SIG_MMI_MidPanelDisChrgCmd, /* [ 69] */
    CAN_DB_SIG_MMI_RefuUnlckReq, /* [ 70] */
    CAN_DB_SIG_MMI_SOCPointSet, /* [ 71] */
    CAN_DB_SIG_EMS_ControlSetSpeed, /* [ 72] */
    CAN_DB_SIG_EMS_CruiseSwitchSts, /* [ 73] */
    CAN_DB_SIG_EMS_CruiseControlSts, /* [ 74] */
    CAN_DB_SIG_EMS_Real_PedalPositionInvalid, /* [ 75] */
    CAN_DB_SIG_EMS_Real_PedalPosition, /* [ 76] */
    CAN_DB_SIG_EMS_FuelPulsesRollingCounter, /* [ 77] */
    CAN_DB_SIG_EMS_EngineSpeedRPM, /* [ 78] */
    CAN_DB_SIG_EMS_EngineSpeedRPMInvalid, /* [ 79] */
    CAN_DB_SIG_EMS_EngStatus, /* [ 80] */
    CAN_DB_SIG_EMS_AccelPedalPosition, /* [ 81] */
    CAN_DB_SIG_EMS_AccelPedalPositionInvalid, /* [ 82] */
    CAN_DB_SIG_EMS_EngineCoolantTemperature, /* [ 83] */
    CAN_DB_SIG_EMS_EngineCoolantTemperatureInva, /* [ 84] */
    CAN_DB_SIG_EMS_EngineSVSTelltale, /* [ 85] */
    CAN_DB_SIG_EMS_EngineMILTelltale, /* [ 86] */
    CAN_DB_SIG_EMS_OilPressureWarning, /* [ 87] */
    CAN_DB_SIG_EMS_Odometerbackup, /* [ 88] */
    CAN_DB_SIG_EMS_LIMSetSpeed, /* [ 89] */
    CAN_DB_SIG_EMS_EAV_ModSetStatus, /* [ 90] */
    CAN_DB_SIG_EMS_LIMControlSts, /* [ 91] */
    CAN_DB_SIG_EMS_LIMmemorySts_Reserved, /* [ 92] */
    CAN_DB_SIG_EMS_LIMSwitchSts, /* [ 93] */
    CAN_DB_SIG_EMS_LIMOverSpdWarningSts, /* [ 94] */
    CAN_DB_SIG_EMS_GPF_Warning, /* [ 95] */
    CAN_DB_SIG_EMS_BrakeOverrideSts, /* [ 96] */
    CAN_DB_SIG_EMS_TankLeakDiagSts, /* [ 97] */
    CAN_DB_SIG_EMS_AdaptiveTargetMode, /* [ 98] */
    CAN_DB_SIG_EMS_DM_ModeProgBar, /* [ 99] */
    CAN_DB_SIG_IPK_IPKEngineTotalOdometer, /* [100] */
    CAN_DB_SIG_IPK_DayToEngSrv, /* [101] */
    CAN_DB_SIG_IPK_ServiceEngineMaintainInterva, /* [102] */
    CAN_DB_SIG_IPK_AirbagUnitLEDSts, /* [103] */
    CAN_DB_SIG_IPK_SVA_AudibleWarningCfgResult, /* [104] */
    CAN_DB_SIG_IPK_FuelLowLevelWarning, /* [105] */
    CAN_DB_SIG_IPK_ESCoffInfo, /* [106] */
    CAN_DB_SIG_IPK_Fail, /* [107] */
    CAN_DB_SIG_IPK_QDashALODFail, /* [108] */
    CAN_DB_SIG_IPK_FuelLevelSts, /* [109] */
    CAN_DB_SIG_IPK_AverageVehicleSpeed, /* [110] */
    CAN_DB_SIG_IPK_HandBrakeSts, /* [111] */
    CAN_DB_SIG_IPK_MaintanceWarningSts, /* [112] */
    CAN_DB_SIG_IPK_LanguageMode, /* [113] */
    CAN_DB_SIG_IPK_EPS_ModSetSelection, /* [114] */
    CAN_DB_SIG_IPK_EPS_DMCorrelativeMode, /* [115] */
    CAN_DB_SIG_IPK_Backlightadjust, /* [116] */
    CAN_DB_SIG_IPK_vDisplay, /* [117] */
    CAN_DB_SIG_IPK_OilLowPressure, /* [118] */
    CAN_DB_SIG_IPK_LIMmemoryEnabe_Reserved, /* [119] */
    CAN_DB_SIG_IPK_BattLowVoltageWarning, /* [120] */
    CAN_DB_SIG_IPK_driving_mode_light_sts, /* [121] */
    CAN_DB_SIG_IPK_AEB_FCWStateReq, /* [122] */
    CAN_DB_SIG_IPK_AEB_AEBStateReq, /* [123] */
    CAN_DB_SIG_IPK_ALOD_ControlTypeReq, /* [124] */
    CAN_DB_SIG_IPK_LCA_EnableStatus, /* [125] */
    CAN_DB_SIG_IPK_RCTA_EnableStatus, /* [126] */
    CAN_DB_SIG_IPK_RCW_EnableStatus, /* [127] */
    CAN_DB_SIG_IPK_AEB_FCWSenlevel, /* [128] */
    CAN_DB_SIG_IPK_LKS_LaneAssistTypeReq, /* [129] */
    CAN_DB_SIG_IPK_LDW_WarningTypeSetting, /* [130] */
    CAN_DB_SIG_IPK_IHBC_MenuReq, /* [131] */
    CAN_DB_SIG_IPK_SLIF_MenuReq, /* [132] */
    CAN_DB_SIG_MAX /* [total] end-of-enum sentinel */
} can_db_sig_id_t_ipk;

#define CAN_DB_IPK_MSG_COUNT  (13u)
#define CAN_DB_IPK_SIG_COUNT  (132u)
#define CAN_DB_IPK_RX_COUNT   (10u)
#define CAN_DB_IPK_TX_COUNT   (3u)

#endif /* CAN_DB_IPK_GEN_H */
