#!/usr/bin/env python3
"""
@brief   Parse a Vector CAN DBC file and emit C-language tables for the
         C02-B2 cluster project.
@brief   解析 Vector CAN DBC 文件, 输出 C02-B2 仪表工程可直接 include 的
         C 语言报文/信号描述表.

@param[in]  argv[1]  path to the input .dbc file
@param[in]  argv[2]  target node name (default: IPK)
@param[in]  argv[3]  max RX messages to emit (default: 64)
@param[in]  argv[4]  max TX messages to emit (default: 9)
@param[out] stdout or --split out_dir writes generated source files

@return  exit 0 on success

Usage:
    python tools/dbc_parse.py <dbc> [node] [rx_n] [tx_n]
    python tools/dbc_parse.py <dbc> IPK 64 9 --split app/drv_api/can
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from typing import List, Optional, Tuple


@dataclass
class Signal:
    name: str
    start_bit: int
    length: int
    byte_order: int
    is_signed: bool
    factor: float
    offset: float
    minimum: float
    maximum: float
    unit: str
    receivers: List[str] = field(default_factory=list)


@dataclass
class Message:
    can_id: int
    name: str
    dlc: int
    transmitter: str
    signals: List[Signal] = field(default_factory=list)


_RE_BO = re.compile(r"^\s*BO_\s+(\d+)\s+(\S+)\s*:\s*(\d+)\s+(\S+)")
# Two-stage SG_ parser: first grab the signal name as the first \S+ token,
# then match the rest. Using a single regex with (\S+)\s*(?:\w+\s*:\s*)? causes
# the re engine to backtrack and truncate the signal name when the optional
# multiplexer group fails to match (e.g. "MMI_Second" -> "MMI_Secon").
_RE_SG_HEAD = re.compile(r"^\s*SG_\s+(\S+)(.*)$")
_RE_SG_REST = re.compile(
    r"^(?:\s+\w+)?\s*:?\s*(\d+)\s*\|\s*(\d+)@\s*([01])([+-])"
    r"\s*\(\s*([-+0-9.eE]+)\s*,\s*([-+0-9.eE]+)\s*\)"
    r"\s*\[\s*([-+0-9.eE]+)\s*\|\s*([-+0-9.eE]+)\s*\]"
    r"\s*\"([^\"]*)\"\s*(.*)$"
)


def parse_dbc(path: str) -> List[Message]:
    msgs: List[Message] = []
    cur: Optional[Message] = None
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            m = _RE_BO.match(line)
            if m:
                can_id = int(m.group(1))
                if can_id >= 0x80000000:
                    cur = None
                    continue
                cur = Message(can_id=can_id, name=m.group(2),
                              dlc=int(m.group(3)), transmitter=m.group(4))
                msgs.append(cur)
                continue
            if cur is None:
                continue
            head = _RE_SG_HEAD.match(line)
            if not head:
                continue
            name = head.group(1)
            rest_str = head.group(2)
            m = _RE_SG_REST.match(rest_str)
            if not m:
                continue
            receivers_raw = m.group(10).strip()
            receivers = [r.strip() for r in receivers_raw.split(",") if r.strip()]
            cur.signals.append(Signal(
                name=name,
                start_bit=int(m.group(1)),
                length=int(m.group(2)),
                byte_order=int(m.group(3)),
                is_signed=(m.group(4) == "-"),
                factor=float(m.group(5)),
                offset=float(m.group(6)),
                minimum=float(m.group(7)),
                maximum=float(m.group(8)),
                unit=m.group(9),
                receivers=receivers,
            ))
    return msgs


def select_for_node(msgs, node, rx_n, tx_n):
    rx = []
    tx = []
    for m in msgs:
        if m.transmitter == node and len(tx) < tx_n:
            tx.append(m)
            continue
        if any(node in s.receivers for s in m.signals):
            if len(rx) < rx_n:
                rx.append(m)
    return rx, tx


def _raw_type_for_length(sig):
    if sig.length <= 8:
        return "I8" if sig.is_signed else "U8"
    if sig.length <= 16:
        return "I16" if sig.is_signed else "U16"
    if sig.length <= 32:
        return "I32" if sig.is_signed else "U32"
    return "I64" if sig.is_signed else "U64"


def _format_float(v):
    if v == int(v):
        return f"{int(v)}.0"
    return f"{v:.8g}"


def emit_header(node, msgs, enum_names):
    guard = f"CAN_DB_{node.upper()}_GEN_H"
    L = []
    L.append("/* AUTOGENERATED by tools/dbc_parse.py -- do not edit by hand. */")
    L.append(f"#ifndef {guard}")
    L.append(f"#define {guard}")
    L.append("")
    L.append("#include <stdint.h>")
    L.append("#include \"can_db_codec.h\"")
    L.append("")
    L.append(f"/* Signal IDs -- order matches can_sig_descs_{node.lower()}[] */")
    L.append("typedef enum {")
    L.append("    CAN_DB_SIG_INVALID = 0, /* [  0] invalid sentinel */")
    # Emit one-based index in the trailing comment for fast lookup
    # against can_sig_descs_<node>[]. The index also matches the
    # "i + 1" mapping used by prv_find_sig_in_msg() in can_tx.c.
    for i, n in enumerate(enum_names, start=1):
        L.append(f"    {n}, /* [{i:>3}] */")
    L.append("    CAN_DB_SIG_MAX /* [total] end-of-enum sentinel */")
    L.append(f"}} can_db_sig_id_t_{node.lower()};")
    L.append("")
    rx_n = sum(1 for m in msgs if m.transmitter != node)
    tx_n = sum(1 for m in msgs if m.transmitter == node)
    L.append(f"#define CAN_DB_{node.upper()}_MSG_COUNT  ({len(msgs)}u)")
    L.append(f"#define CAN_DB_{node.upper()}_SIG_COUNT  ({len(enum_names)}u)")
    L.append(f"#define CAN_DB_{node.upper()}_RX_COUNT   ({rx_n}u)")
    L.append(f"#define CAN_DB_{node.upper()}_TX_COUNT   ({tx_n}u)")
    L.append("")
    L.append(f"#endif /* {guard} */")
    L.append("")
    return "\n".join(L)


def emit_source(node, msgs, enum_names):
    L = []
    L.append("/* AUTOGENERATED by tools/dbc_parse.py -- do not edit by hand. */")
    L.append(f"#include \"can_db_{node.lower()}_gen.h\"")
    L.append("")
    L.append("/* === Per-signal descriptors === */")
    L.append(f"const can_sig_desc_t can_sig_descs_{node.lower()}[] = {{")
    for m in msgs:
        for s in m.signals:
            raw_t = "CAN_RAW_" + _raw_type_for_length(s)
            L.append(
                f"    {{ /* {s.name} in {m.name} */\n"
                f"        .start_bit    = {s.start_bit},\n"
                f"        .length       = {s.length},\n"
                f"        .byte_order   = {s.byte_order},\n"
                f"        .is_signed    = {1 if s.is_signed else 0},\n"
                f"        .factor       = {_format_float(s.factor)}f,\n"
                f"        .offset       = {_format_float(s.offset)}f,\n"
                f"        .raw_type     = {raw_t},\n"
                f"    }},"
            )
    L.append("};")
    L.append("")
    L.append("/* === Per-message descriptors === */")
    L.append(f"const can_msg_desc_t can_msg_descs_{node.lower()}[] = {{")
    sig_index = 0
    for m in msgs:
        n = len(m.signals)
        L.append(
            f"    {{ /* {m.name} */\n"
            f"        .can_id     = 0x{m.can_id:04X}u,\n"
            f"        .dlc        = {m.dlc}u,\n"
            f"        .name       = \"{m.name}\",\n"
            f"        .sig_index  = {sig_index}u,\n"
            f"        .sig_count  = {n}u,\n"
            f"        .tx_node    = \"{m.transmitter}\",\n"
            f"        .is_tx      = {(1 if m.transmitter == node else 0)},\n"
            f"    }},"
        )
        sig_index += n
    L.append("};")
    L.append("")
    L.append("/* === Index tables (RX / TX) === */")
    rx_idx = [i for i, m in enumerate(msgs) if m.transmitter != node]
    tx_idx = [i for i, m in enumerate(msgs) if m.transmitter == node]
    L.append(f"const uint16_t can_db_{node.lower()}_rx_idx[] = {{")
    L.append("    " + (", ".join(f"{i}u" for i in rx_idx) + ("," if rx_idx else "")))
    L.append("};")
    L.append(f"const uint16_t can_db_{node.lower()}_tx_idx[] = {{")
    L.append("    " + (", ".join(f"{i}u" for i in tx_idx) + ("," if tx_idx else "")))
    L.append("};")
    L.append("")
    L.append(f"#define CAN_DB_{node.upper()}_RX_COUNT  ({len(rx_idx)}u)")
    L.append(f"#define CAN_DB_{node.upper()}_TX_COUNT  ({len(tx_idx)}u)")
    L.append("")
    return "\n".join(L)


def main():
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    dbc_path = sys.argv[1]
    node = sys.argv[2] if len(sys.argv) > 2 else "IPK"
    # IPK node defaults to 64 RX + 9 TX per C02-B2 cluster DBC.
    rx_n = int(sys.argv[3]) if len(sys.argv) > 3 else 64
    tx_n = int(sys.argv[4]) if len(sys.argv) > 4 else 9

    all_msgs = parse_dbc(dbc_path)
    rx, tx = select_for_node(all_msgs, node, rx_n, tx_n)
    selected = rx + tx

    enum_names = []
    for m in selected:
        for s in m.signals:
            enum_names.append("CAN_DB_SIG_" + s.name)

    header = emit_header(node, selected, enum_names)
    source = emit_source(node, selected, enum_names)

    if "--split" in sys.argv:
        out_dir = sys.argv[sys.argv.index("--split") + 1]
        with open(f"{out_dir}/can_db_{node.lower()}_gen.h", "w", encoding="utf-8") as f:
            f.write(header)
        with open(f"{out_dir}/can_db_{node.lower()}_gen.c", "w", encoding="utf-8") as f:
            f.write(source)
    else:
        sys.stdout.write(f"/* === FILE: can_db_{node.lower()}_gen.h === */\n")
        sys.stdout.write(header)
        sys.stdout.write(f"/* === FILE: can_db_{node.lower()}_gen.c === */\n")
        sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    sys.exit(main())
